API: OpenSim::MarkerPlacer Class Reference
OpenSim::MarkerPlacer Class Reference
A class implementing a set of parameters describing how to place markers on a model (presumably after it has been scaled to fit a subject).
Public Member Functions
MarkerPlacer ()
MarkerPlacer (const MarkerPlacer &aMarkerPlacementParams)
virtual ~MarkerPlacer ()
void copyData (const MarkerPlacer &aMarkerPlacementParams)
MarkerPlacer & operator= (const MarkerPlacer &aMarkerPlacementParams)
bool processModel (Model *aModel, const std::string &aPathToSubject="") const
bool getApply () const
void setApply (bool aApply)
const std::string & getStaticPoseFileName () const
void setStaticPoseFileName (const std::string &aFileName)
const Array< double > & getTimeRange () const
void setTimeRange (const Array< double > &timeRange)
IKTaskSet & getIKTaskSet ()
const std::string & getCoordinateFileName () const
void setCoordinateFileName (const std::string &aCoordinateFileName)
const std::string & getMarkerFileName () const
void setMarkerFileName (const std::string &aMarkerFileName)
double getMaxMarkerMovement () const
void setMaxMarkerMovement (double aMaxMarkerMovement)
const std::string & getOutputModelFileName () const
void setOutputModelFileName (const std::string &aOutputModelFileName)
const std::string & getOutputMarkerFileName () const
void setOutputMarkerFileName (const std::string &outputMarkerFileName)
const std::string & getOutputMotionFileName () const
void setOutputMotionFileName (const std::string &outputMotionFileName)
void setPrintResultFiles (bool aToWrite)
bool getMoveModelMarkers ()
void setMoveModelMarkers (bool aMove)
Storage * getOutputStorage ()
Public Member Functions inherited from OpenSim::Object
virtual ~Object ()
Virtual destructor for cleanup.
bool isEqualTo (const Object &aObject) const
Equality operator wrapper for use from languages not supporting operator overloading.
Object & operator= (const Object &aObject)
Copy assignment copies he base class fields, including the properties.
virtual bool operator== (const Object &aObject) const
Determine if two objects are equal.
virtual bool operator< (const Object &aObject) const
Provide an ordering for objects so they can be put in sorted containers.
void setName (const std::string &name)
Set the name of the Object.
const std::string & getName () const
Get the name of this Object.
void setDescription (const std::string &description)
Set description, a one-liner summary.
const std::string & getDescription () const
Get description, a one-liner summary.
const std::string & getAuthors () const
Get Authors of this Object.
void setAuthors (const std::string &authors)
Set Authors of this object.
const std::string & getReferences () const
Get references or publications to cite if using this object.
void setReferences (const std::string &references)
Set references or publications to cite if using this object.
int getNumProperties () const
Determine how many properties are stored with this Object.
const AbstractProperty & getPropertyByIndex (int propertyIndex) const
Get a const reference to a property by its index number, returned as an AbstractProperty.
AbstractProperty & updPropertyByIndex (int propertyIndex)
Get a writable reference to a property by its index number, returned as an AbstractProperty.
bool hasProperty (const std::string &name) const
Return true if this Object has a property of any type with the given name, which must not be empty.
const AbstractProperty & getPropertyByName (const std::string &name) const
Get a const reference to a property by its name, returned as an AbstractProperty.
AbstractProperty & updPropertyByName (const std::string &name)
Get a writable reference to a property by its name, returned as an AbstractProperty.
template<class T >
bool hasProperty () const
Return true if this Object contains an unnamed, one-object property that contains objects of the given template type T.
template<class T >
const Property< T > & getProperty (const PropertyIndex &index) const
Get property of known type Property<T> as a const reference; the property must be present and have the right type.
template<class T >
Property< T > & updProperty (const PropertyIndex &index)
Get property of known type Property<T> as a writable reference; the property must be present and have the right type.
bool isObjectUpToDateWithProperties () const
Returns true if no property's value has changed since the last time setObjectIsUpToDateWithProperties() was called.
void readObjectFromXMLNodeOrFile (SimTK::Xml::Element &objectElement, int versionNumber)
We're given an XML element from which we are to populate this Object.
virtual void updateFromXMLNode (SimTK::Xml::Element &objectElement, int versionNumber)
Use this method to deserialize an object from a SimTK::Xml::Element.
void updateXMLNode (SimTK::Xml::Element &parent, const AbstractProperty *prop=nullptr) const
Serialize this object into the XML node that represents it.
bool getInlined () const
Inlined means an in-memory Object that is not associated with an XMLDocument.
void setInlined (bool aInlined, const std::string &aFileName="")
Mark this as inlined or not and optionally provide a file name to associate with the new XMLDocument for the non-inline case.
std::string getDocumentFileName () const
If there is a document associated with this object then return the file name maintained by the document.
int getDocumentFileVersion () const
If there is a document associated with this object then return its version number.
void setAllPropertiesUseDefault (bool aUseDefault)
bool print (const std::string &fileName) const
Write this Object into an XML file of the given name; conventionally the suffix to use is ".osim".
std::string dump () const
dump the XML representation of this Object into an std::string and return it.
virtual bool isA (const char *type) const
The default implementation returns true only if the supplied string is "Object"; each Object-derived class overrides this to match its own class name.
const std::string & toString () const
Wrapper to be used on Java side to display objects in tree; this returns just the object's name.
PropertySet & getPropertySet ()
OBSOLETE: Get a reference to the PropertySet maintained by the Object.
const PropertySet & getPropertySet () const
Static Public Member Functions
Auto-generated functions
static MarkerPlacer * safeDownCast (OpenSim::Object *obj)
For use in MATLAB and Python to access the concrete class.
Static Public Member Functions inherited from OpenSim::Object
static void registerType (const Object &defaultObject)
Register an instance of a class; if the class is already registered it will be replaced.
static void renameType (const std::string &oldTypeName, const std::string &newTypeName)
Support versioning by associating the current Object type with an old name.
static const Object * getDefaultInstanceOfType (const std::string &concreteClassName)
Return a pointer to the default instance of the registered (concrete) Object whose class name is given, or NULL if the type is not registered.
template<class T >
static bool isObjectTypeDerivedFrom (const std::string &concreteClassName)
Return true if the given concrete object type represents a subclass of the template object type T, and thus could be referenced with a T*.
static Object * newInstanceOfType (const std::string &concreteClassName)
Create a new instance of the concrete Object type whose class name is given as concreteClassName.
static void getRegisteredTypenames (Array< std::string > &typeNames)
Retrieve all the typenames registered so far.
template<class T >
static void getRegisteredObjectsOfGivenType (ArrayPtrs< T > &rArray)
Return an array of pointers to the default instances of all registered (concrete) Object types that derive from a given Object-derived type that does not have to be concrete.
static bool PrintPropertyInfo (std::ostream &os, const std::string &classNameDotPropertyName, bool printFlagInfo=true)
Dump formatted property information to a given output stream, useful for creating a "help" facility for registered objects.
static bool PrintPropertyInfo (std::ostream &os, const std::string &className, const std::string &propertyName, bool printFlagInfo=true)
Same as the other signature but the class name and property name are provided as two separate strings.
static Object * makeObjectFromFile (const std::string &fileName)
Create an OpenSim object whose type is based on the tag at the root node of the XML file passed in.
static const std::string & getClassName ()
Return the name of this class as a string; i.e., "Object".
static void setSerializeAllDefaults (bool shouldSerializeDefaults)
Static function to control whether all registered objects and their properties are written to the defaults section of output files rather than only those values for which the default was explicitly overwritten when read in from an input file or set programmatically.
static bool getSerializeAllDefaults ()
Report the value of the "serialize all defaults" flag.
static bool isKindOf (const char *type)
Returns true if the passed-in string is "Object"; each Object-derived class defines a method of this name for its own class name.
static void setDebugLevel (int newLevel)
Set the amount of logging output.
static int getDebugLevel ()
Get the current setting of debug level.
static Object * SafeCopy (const Object *aObject)
Use the clone() method to duplicate the given object unless the pointer is null in which case null is returned.
static void RegisterType (const Object &defaultObject)
OBSOLETE alternate name for registerType().
static void RenameType (const std::string &oldName, const std::string &newName)
OBSOLETE alternate name for renameType().
Auto-generated functions <br>
static const std::string & getClassName ()
This returns "MarkerPlacer"
MarkerPlacer * clone () const override
Create a new heap-allocated copy of the concrete object to which this Object refers.
const std::string & getConcreteClassName () const override
Returns the class name of the concrete Object-derived class of the actual object referenced by this Object, as a string.
Detailed Description
A class implementing a set of parameters describing how to place markers on a model (presumably after it has been scaled to fit a subject).
MarkerPlacer is bundled with ModelScaler and GenericModelMaker to form the ScaleTool
Author
Peter Loan
Version
1.0
Constructor & Destructor Documentation
MarkerPlacer() [1/2]
OpenSim::MarkerPlacer::MarkerPlacer ()
MarkerPlacer() [2/2]
OpenSim::MarkerPlacer::MarkerPlacer (const MarkerPlacer & aMarkerPlacementParams)
~MarkerPlacer()
virtual OpenSim::MarkerPlacer::~MarkerPlacer () virtual
Member Function Documentation
clone()
MarkerPlacer * OpenSim::MarkerPlacer::clone () const inline override virtual
Create a new heap-allocated copy of the concrete object to which this Object refers.
It is up to the caller to delete the returned object when no longer needed. Every concrete object deriving from Object implements this pure virtual method automatically, via the declaration macro it invokes (e.g., OpenSim_DECLARE_CONCRETE_OBJECT()). Note that the concrete class overrides modify the return type to be a pointer to the concrete object; that still overrides the base class method because the return type is covariant with (that is, derives from) Object.
Implements OpenSim::Object.
copyData()
void OpenSim::MarkerPlacer::copyData (const MarkerPlacer & aMarkerPlacementParams)
getApply()
bool OpenSim::MarkerPlacer::getApply () const inline
getClassName()
static const std::string & OpenSim::MarkerPlacer::getClassName () inline static
This returns "MarkerPlacer"
See getConcreteClassName() if you want the class name of the underlying concrete object instead.
getConcreteClassName()
const std::string & OpenSim::MarkerPlacer::getConcreteClassName () const inline override virtual
Returns the class name of the concrete Object-derived class of the actual object referenced by this Object, as a string.
This is the string that is used as the tag for this concrete object in an XML file. Every concrete class derived from Object automatically overrides this method via the declaration macro it uses. See getClassName() to get the class name of the referencing (possibly abstract) class rather than the concrete object.
See also
getClassName()
Implements OpenSim::Object.
getCoordinateFileName()
const std::string & OpenSim::MarkerPlacer::getCoordinateFileName () const inline
getIKTaskSet()
IKTaskSet & OpenSim::MarkerPlacer::getIKTaskSet () inline
getMarkerFileName()
const std::string & OpenSim::MarkerPlacer::getMarkerFileName () const inline
getMaxMarkerMovement()
double OpenSim::MarkerPlacer::getMaxMarkerMovement () const inline
getMoveModelMarkers()
bool OpenSim::MarkerPlacer::getMoveModelMarkers () inline
getOutputMarkerFileName()
const std::string & OpenSim::MarkerPlacer::getOutputMarkerFileName () const inline
getOutputModelFileName()
const std::string & OpenSim::MarkerPlacer::getOutputModelFileName () const inline
getOutputMotionFileName()
const std::string & OpenSim::MarkerPlacer::getOutputMotionFileName () const inline
getOutputStorage()
Storage * OpenSim::MarkerPlacer::getOutputStorage ()
getStaticPoseFileName()
const std::string & OpenSim::MarkerPlacer::getStaticPoseFileName () const inline
getTimeRange()
const Array< double > & OpenSim::MarkerPlacer::getTimeRange () const inline
operator=()
MarkerPlacer & OpenSim::MarkerPlacer::operator= (const MarkerPlacer & aMarkerPlacementParams)
processModel()
bool OpenSim::MarkerPlacer::processModel (Model * aModel, const std::string & aPathToSubject = "") const
safeDownCast()
static MarkerPlacer * OpenSim::MarkerPlacer::safeDownCast (OpenSim::Object * obj) inline static
For use in MATLAB and Python to access the concrete class.
Example: cObj = MarkerPlacer.safeDownCast(obj). This is equivalent to dynamic_cast<MarkerPlacer*>(obj) in C++.
setApply()
void OpenSim::MarkerPlacer::setApply (bool aApply) inline
References OpenSim::AbstractProperty::setValueIsDefault().
setCoordinateFileName()
void OpenSim::MarkerPlacer::setCoordinateFileName (const std::string & aCoordinateFileName) inline
References OpenSim::AbstractProperty::setValueIsDefault().
setMarkerFileName()
void OpenSim::MarkerPlacer::setMarkerFileName (const std::string & aMarkerFileName) inline
References OpenSim::AbstractProperty::setValueIsDefault().
setMaxMarkerMovement()
void OpenSim::MarkerPlacer::setMaxMarkerMovement (double aMaxMarkerMovement) inline
References OpenSim::AbstractProperty::setValueIsDefault().
setMoveModelMarkers()
void OpenSim::MarkerPlacer::setMoveModelMarkers (bool aMove) inline
setOutputMarkerFileName()
void OpenSim::MarkerPlacer::setOutputMarkerFileName (const std::string & outputMarkerFileName) inline
References OpenSim::AbstractProperty::setValueIsDefault().
setOutputModelFileName()
void OpenSim::MarkerPlacer::setOutputModelFileName (const std::string & aOutputModelFileName) inline
References OpenSim::AbstractProperty::setValueIsDefault().
setOutputMotionFileName()
void OpenSim::MarkerPlacer::setOutputMotionFileName (const std::string & outputMotionFileName) inline
References OpenSim::AbstractProperty::setValueIsDefault().
setPrintResultFiles()
void OpenSim::MarkerPlacer::setPrintResultFiles (bool aToWrite) inline
Referenced by OpenSim::ScaleTool::setPrintResultFiles().
setStaticPoseFileName()
void OpenSim::MarkerPlacer::setStaticPoseFileName (const std::string & aFileName) inline
References OpenSim::AbstractProperty::setValueIsDefault().
setTimeRange()
void OpenSim::MarkerPlacer::setTimeRange (const Array< double > & timeRange) inline
References OpenSim::AbstractProperty::setValueIsDefault().
The documentation for this class was generated from the following file:
OpenSim/Tools/MarkerPlacer.h