API: OpenSim::ValueArrayDictionary Class Reference
OpenSim::ValueArrayDictionary Class Reference
ValueArrayDictionary represents an associative array mapping from a string to an AbstractValueArray.
Public Member Functions
bool hasKey (const std::string &key) const
Does a key-value pair corresponding to the given key currently exist ?
const AbstractValue & getValueForKey (const std::string &key) const
Get the first entry of the array corresponding to the given key.
template<typename ValueType >
bool setValueForKey (const std::string &key, const ValueType &value)
Set the value corresponding to a given key.
const AbstractValueArray & getValueArrayForKey (const std::string &key) const
Get the array corresponding to a given key.
bool setValueArrayForKey (const std::string &key, const AbstractValueArray &abstractValueArray)
Set the array corresponding to a given key.
AbstractValueArray & updValueArrayForKey (const std::string &key)
Get a writable reference to the array corresponding to a given key.
void removeValueForKey (const std::string &key)
Remove a key and its associated array.
void removeValueArrayForKey (const std::string &key)
Remove a key and its associated array.
std::vector< std::string > getKeys () const
Get all the existing keys as a std::vector.
Dictionary::const_iterator getKeyValueBegin () const
Get begin iterator to the associative array.
Dictionary::const_iterator getKeyValueEnd () const
Get begin iterator to the associative array.
std::string getValueAsString (const std::string &key) const
Get value corresponding to the given key as string.
Detailed Description
ValueArrayDictionary represents an associative array mapping from a string to an AbstractValueArray.
Member Typedef Documentation
AbstractValue
using OpenSim::ValueArrayDictionary::AbstractValue = SimTK::AbstractValue
Member Function Documentation
getKeys()
std::vector< std::string > OpenSim::ValueArrayDictionary::getKeys () const inline
Get all the existing keys as a std::vector.
Referenced by OpenSim::DataTable_< ETX, ETY >::DataTable_(), and OpenSim::DataTable_< ETX, ETY >::validateDependentsMetaData().
getKeyValueBegin()
Dictionary::const_iterator OpenSim::ValueArrayDictionary::getKeyValueBegin () const inline
Get begin iterator to the associative array.
getKeyValueEnd()
Dictionary::const_iterator OpenSim::ValueArrayDictionary::getKeyValueEnd () const inline
Get begin iterator to the associative array.
getValueArrayForKey()
const AbstractValueArray & OpenSim::ValueArrayDictionary::getValueArrayForKey (const std::string & key) const inline
Get the array corresponding to a given key.
Exceptions
KeyNotFound If key is not found.
References hasKey().
Referenced by OpenSim::DataTable_< ETX, ETY >::appendRow(), and OpenSim::DataTable_< ETX, ETY >::validateDependentsMetaData().
getValueAsString()
std::string OpenSim::ValueArrayDictionary::getValueAsString (const std::string & key) const inline
Get value corresponding to the given key as string.
Exceptions
KeyNotFound If key is not found.
References hasKey().
getValueForKey()
const AbstractValue & OpenSim::ValueArrayDictionary::getValueForKey (const std::string & key) const inline
Get the first entry of the array corresponding to the given key.
Exceptions
KeyNotFound If key is not found.
References hasKey().
Referenced by OpenSim::DataTable_< ETX, ETY >::validateIndependentMetaData().
hasKey()
bool OpenSim::ValueArrayDictionary::hasKey (const std::string & key) const inline
Does a key-value pair corresponding to the given key currently exist ?
Referenced by OpenSim::DataTable_< ETX, ETY >::appendRow(), getValueArrayForKey(), getValueAsString(), getValueForKey(), updValueArrayForKey(), and OpenSim::DataTable_< ETX, ETY >::validateDependentsMetaData().
removeValueArrayForKey()
void OpenSim::ValueArrayDictionary::removeValueArrayForKey (const std::string & key) inline
Remove a key and its associated array.
Referenced by OpenSim::DataTable_< ETX, ETY >::DataTable_().
removeValueForKey()
void OpenSim::ValueArrayDictionary::removeValueForKey (const std::string & key) inline
Remove a key and its associated array.
setValueArrayForKey()
bool OpenSim::ValueArrayDictionary::setValueArrayForKey (const std::string & key, const AbstractValueArray & abstractValueArray) inline
Set the array corresponding to a given key.
Value array is set only if the key does not already exist.
Return values
true If the value was set for the given key.
false If the value was not set because key already present.
References OpenSim::AbstractValueArray::clone().
setValueForKey()
template<typename ValueType > bool OpenSim::ValueArrayDictionary::setValueForKey (const std::string & key, const ValueType & value) inline
Set the value corresponding to a given key.
Value is set only if the key does not already exist.
Return values
true If the value was set for the given key.
false If the value was not set because key already present.
References OpenSim::ValueArray< T >::upd().
Referenced by OpenSim::DelimFileAdapter< T >::extendRead().
updValueArrayForKey()
AbstractValueArray & OpenSim::ValueArrayDictionary::updValueArrayForKey (const std::string & key) inline
Get a writable reference to the array corresponding to a given key.
Exceptions
KeyNotFound If key is not found.
References hasKey().
Referenced by OpenSim::DataTable_< ETX, ETY >::DataTable_().
The documentation for this class was generated from the following file:
OpenSim/Common/ValueArrayDictionary.h