API: OpenSim::MocoTropterSolver::ExplicitTropterProblem< T > Class Template Reference
OpenSim::MocoTropterSolver::ExplicitTropterProblem< T > Class Template Reference
Public Member Functions
ExplicitTropterProblem (const MocoTropterSolver &solver)
void initialize_on_mesh (const Eigen::VectorXd &) const override
void calc_differential_algebraic_equations (const tropter::Input< T > &in, tropter::Output< T > out) const override
Public Member Functions inherited from OpenSim::MocoTropterSolver::TropterProblemBase< T >
template<typename MocoTrajectoryType , typename tropIterateType >
MocoTrajectoryType convertIterateTropterToMoco (const tropIterateType &tropSol) const
MocoTrajectory convertToMocoTrajectory (const tropter::Iterate &tropSol) const
MocoSolution convertToMocoSolution (const tropter::Solution &tropSol) const
tropter::Iterate convertToTropterIterate (const MocoTrajectory &mocoIter) const
Constructor & Destructor Documentation
ExplicitTropterProblem()
template<typename T > OpenSim::MocoTropterSolver::ExplicitTropterProblem< T >::ExplicitTropterProblem (const MocoTropterSolver & solver) inline
Member Function Documentation
calc_differential_algebraic_equations()
template<typename T > void OpenSim::MocoTropterSolver::ExplicitTropterProblem< T >::calc_differential_algebraic_equations (const tropter::Input< T > & in, tropter::Output< T > out) const inline override
References OpenSim::MocoTropterSolver::TropterProblemBase< T >::calcKinematicConstraintErrors(), OpenSim::MocoTropterSolver::TropterProblemBase< T >::calcPathConstraintErrors(), OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_modelBase, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_modelDisabledConstraints, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_stateBase, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_stateDisabledConstraints, OpenSim::MocoTropterSolver::TropterProblemBase< T >::qdot, OpenSim::MocoTropterSolver::TropterProblemBase< T >::qdotCorr, and OpenSim::MocoTropterSolver::TropterProblemBase< T >::setSimTKState().
initialize_on_mesh()
template<typename T > void OpenSim::MocoTropterSolver::ExplicitTropterProblem< T >::initialize_on_mesh (const Eigen::VectorXd &) const inline override
The documentation for this class was generated from the following file:
OpenSim/Moco/tropter/TropterProblem.h