API: OpenSim::ModelComponent Class Reference
OpenSim::ModelComponent Class Reference abstract
This defines the abstract ModelComponent class, which is used to specify components of a musculoskeletal model and the elements they add to the underlying computational SimTK::System (MultibodySystem).
Public Member Functions
ModelComponent ()
Default constructor.
ModelComponent (const std::string &aFileName, bool aUpdateFromXMLNode=true)
Construct ModelComponent from an XML file.
ModelComponent (SimTK::Xml::Element &aNode)
Construct ModelComponent from a specific node in an XML document.
virtual ~ModelComponent ()
Destructor is virtual to allow concrete model component cleanup.
void connectToModel (Model &model)
Connect this ModelComponent to its aggregate- a Model.
const Model & getModel () const
Get a const reference to the Model this component is part of.
Model & updModel ()
Get a modifiable reference to the Model this component is part of.
bool hasModel () const
Does this ModelComponent have a Model associated with it?
void preScale (const SimTK::State &s, const ScaleSet &scaleSet)
Perform any computations that must occur before ModelComponent::scale() is invoked on all ModelComponents in the Model.
void scale (const SimTK::State &s, const ScaleSet &scaleSet)
Scale the ModelComponent.
void postScale (const SimTK::State &s, const ScaleSet &scaleSet)
Perform any computations that must occur after ModelComponent::scale() has been invoked on all ModelComponents in the Model.
Public Member Functions inherited from OpenSim::Component
Public Member Functions inherited from OpenSim::Object
virtual ~Object ()
Virtual destructor for cleanup.
bool isEqualTo (const Object &aObject) const
Equality operator wrapper for use from languages not supporting operator overloading.
Object & operator= (const Object &aObject)
Copy assignment copies he base class fields, including the properties.
virtual bool operator== (const Object &aObject) const
Determine if two objects are equal.
virtual bool operator< (const Object &aObject) const
Provide an ordering for objects so they can be put in sorted containers.
void setName (const std::string &name)
Set the name of the Object.
const std::string & getName () const
Get the name of this Object.
void setDescription (const std::string &description)
Set description, a one-liner summary.
const std::string & getDescription () const
Get description, a one-liner summary.
const std::string & getAuthors () const
Get Authors of this Object.
void setAuthors (const std::string &authors)
Set Authors of this object.
const std::string & getReferences () const
Get references or publications to cite if using this object.
void setReferences (const std::string &references)
Set references or publications to cite if using this object.
int getNumProperties () const
Determine how many properties are stored with this Object.
const AbstractProperty & getPropertyByIndex (int propertyIndex) const
Get a const reference to a property by its index number, returned as an AbstractProperty.
AbstractProperty & updPropertyByIndex (int propertyIndex)
Get a writable reference to a property by its index number, returned as an AbstractProperty.
bool hasProperty (const std::string &name) const
Return true if this Object has a property of any type with the given name, which must not be empty.
const AbstractProperty & getPropertyByName (const std::string &name) const
Get a const reference to a property by its name, returned as an AbstractProperty.
AbstractProperty & updPropertyByName (const std::string &name)
Get a writable reference to a property by its name, returned as an AbstractProperty.
template<class T >
bool hasProperty () const
Return true if this Object contains an unnamed, one-object property that contains objects of the given template type T.
template<class T >
const Property< T > & getProperty (const PropertyIndex &index) const
Get property of known type Property<T> as a const reference; the property must be present and have the right type.
template<class T >
Property< T > & updProperty (const PropertyIndex &index)
Get property of known type Property<T> as a writable reference; the property must be present and have the right type.
bool isObjectUpToDateWithProperties () const
Returns true if no property's value has changed since the last time setObjectIsUpToDateWithProperties() was called.
void readObjectFromXMLNodeOrFile (SimTK::Xml::Element &objectElement, int versionNumber)
We're given an XML element from which we are to populate this Object.
void updateXMLNode (SimTK::Xml::Element &parent, const AbstractProperty *prop=nullptr) const
Serialize this object into the XML node that represents it.
bool getInlined () const
Inlined means an in-memory Object that is not associated with an XMLDocument.
void setInlined (bool aInlined, const std::string &aFileName="")
Mark this as inlined or not and optionally provide a file name to associate with the new XMLDocument for the non-inline case.
std::string getDocumentFileName () const
If there is a document associated with this object then return the file name maintained by the document.
int getDocumentFileVersion () const
If there is a document associated with this object then return its version number.
void setAllPropertiesUseDefault (bool aUseDefault)
bool print (const std::string &fileName) const
Write this Object into an XML file of the given name; conventionally the suffix to use is ".osim".
std::string dump () const
dump the XML representation of this Object into an std::string and return it.
virtual bool isA (const char *type) const
The default implementation returns true only if the supplied string is "Object"; each Object-derived class overrides this to match its own class name.
const std::string & toString () const
Wrapper to be used on Java side to display objects in tree; this returns just the object's name.
PropertySet & getPropertySet ()
OBSOLETE: Get a reference to the PropertySet maintained by the Object.
const PropertySet & getPropertySet () const
Static Public Member Functions
Auto-generated functions
static ModelComponent * safeDownCast (OpenSim::Object *obj)
For use in MATLAB and Python to access the concrete class.
Static Public Member Functions inherited from OpenSim::Component
static Component * safeDownCast (OpenSim::Object *obj)
For use in MATLAB and Python to access the concrete class.
static const std::string & getClassName ()
This returns "Component"
Static Public Member Functions inherited from OpenSim::Object
static void registerType (const Object &defaultObject)
Register an instance of a class; if the class is already registered it will be replaced.
static void renameType (const std::string &oldTypeName, const std::string &newTypeName)
Support versioning by associating the current Object type with an old name.
static const Object * getDefaultInstanceOfType (const std::string &concreteClassName)
Return a pointer to the default instance of the registered (concrete) Object whose class name is given, or NULL if the type is not registered.
template<class T >
static bool isObjectTypeDerivedFrom (const std::string &concreteClassName)
Return true if the given concrete object type represents a subclass of the template object type T, and thus could be referenced with a T*.
static Object * newInstanceOfType (const std::string &concreteClassName)
Create a new instance of the concrete Object type whose class name is given as concreteClassName.
static void getRegisteredTypenames (Array< std::string > &typeNames)
Retrieve all the typenames registered so far.
template<class T >
static void getRegisteredObjectsOfGivenType (ArrayPtrs< T > &rArray)
Return an array of pointers to the default instances of all registered (concrete) Object types that derive from a given Object-derived type that does not have to be concrete.
static bool PrintPropertyInfo (std::ostream &os, const std::string &classNameDotPropertyName, bool printFlagInfo=true)
Dump formatted property information to a given output stream, useful for creating a "help" facility for registered objects.
static bool PrintPropertyInfo (std::ostream &os, const std::string &className, const std::string &propertyName, bool printFlagInfo=true)
Same as the other signature but the class name and property name are provided as two separate strings.
static Object * makeObjectFromFile (const std::string &fileName)
Create an OpenSim object whose type is based on the tag at the root node of the XML file passed in.
static const std::string & getClassName ()
Return the name of this class as a string; i.e., "Object".
static void setSerializeAllDefaults (bool shouldSerializeDefaults)
Static function to control whether all registered objects and their properties are written to the defaults section of output files rather than only those values for which the default was explicitly overwritten when read in from an input file or set programmatically.
static bool getSerializeAllDefaults ()
Report the value of the "serialize all defaults" flag.
static bool isKindOf (const char *type)
Returns true if the passed-in string is "Object"; each Object-derived class defines a method of this name for its own class name.
static void setDebugLevel (int newLevel)
Set the amount of logging output.
static int getDebugLevel ()
Get the current setting of debug level.
static Object * SafeCopy (const Object *aObject)
Use the clone() method to duplicate the given object unless the pointer is null in which case null is returned.
static void RegisterType (const Object &defaultObject)
OBSOLETE alternate name for registerType().
static void RenameType (const std::string &oldName, const std::string &newName)
OBSOLETE alternate name for renameType().
ModelComponent System Creation and Access Methods
These methods support implementing concrete ModelComponents.
Add methods can only be called inside of extendAddToSystem() and are useful for creating the underlying SimTK::System level variables that are used for computing values of interest.
Warning
Accessors for System indices are intended for component internal use only.
SimTK::ReferencePtr< Model > _model
The model this component belongs to.
void updateFromXMLNode (SimTK::Xml::Element &aNode, int versionNumber) override
Use this method to deserialize an object from a SimTK::Xml::Element.
Auto-generated functions <br>
static const std::string & getClassName ()
This returns "ModelComponent"
ModelComponent * clone () const override=0
Create a new heap-allocated copy of the concrete object to which this Object refers.
const std::string & getConcreteClassName () const override=0
Returns the class name of the concrete Object-derived class of the actual object referenced by this Object, as a string.
Detailed Description
This defines the abstract ModelComponent class, which is used to specify components of a musculoskeletal model and the elements they add to the underlying computational SimTK::System (MultibodySystem).
A ModelComponent is an OpenSim::Component and therefore has the capabilities to add necessary system resources to the System and to manage access to those resources (
See also
Component)
Bodies, Joints, Coordinates, Constraints, Forces, Actuators, Controllers, and even Model itself, are ModelComponents. Each component is "connected" to a model and an underlying SimTK::Subsystem, which by default is the System's DefaultSubsystem.
The primary responsibility of a ModelComponent is to add its computational representation(s) of physical musculoskeletal structures to the underlying SimTK::System by implementing extendAddToSystem().
Additional methods provide support for adding modeling options, state and cache variables (
See also
Component).
Public methods enable access to component variables via their names.
Author
Ajay Seth, Michael Sherman
Constructor & Destructor Documentation
ModelComponent() [1/3]
OpenSim::ModelComponent::ModelComponent ()
Default constructor.
ModelComponent() [2/3]
OpenSim::ModelComponent::ModelComponent (const std::string & aFileName, bool aUpdateFromXMLNode = true)
Construct ModelComponent from an XML file.
ModelComponent() [3/3]
OpenSim::ModelComponent::ModelComponent (SimTK::Xml::Element & aNode) explicit
Construct ModelComponent from a specific node in an XML document.
~ModelComponent()
virtual OpenSim::ModelComponent::~ModelComponent () inline virtual
Destructor is virtual to allow concrete model component cleanup.
Member Function Documentation
clone()
ModelComponent * OpenSim::ModelComponent::clone () const override pure virtual
Create a new heap-allocated copy of the concrete object to which this Object refers.
It is up to the caller to delete the returned object when no longer needed. Every concrete object deriving from Object implements this pure virtual method automatically, via the declaration macro it invokes (e.g., OpenSim_DECLARE_CONCRETE_OBJECT()). Note that the concrete class overrides modify the return type to be a pointer to the concrete object; that still overrides the base class method because the return type is covariant with (that is, derives from) Object.
Implements OpenSim::Component.
Implemented in OpenSim::ActivationCoordinateActuator, OpenSim::BodyActuator, OpenSim::ClutchedPathSpring, OpenSim::ConstantMuscleActivation, OpenSim::CoordinateActuator, OpenSim::DeGrooteFregly2016Muscle, OpenSim::Delp1990Muscle_Deprecated, OpenSim::FirstOrderMuscleActivationDynamics, OpenSim::McKibbenActuator, OpenSim::Millard2012AccelerationMuscle, OpenSim::Millard2012EquilibriumMuscle, OpenSim::MuscleFirstOrderActivationDynamicModel, OpenSim::MuscleFixedWidthPennationModel, OpenSim::PointActuator, OpenSim::PointToPointActuator, OpenSim::RigidTendonMuscle, OpenSim::Schutte1993Muscle_Deprecated, OpenSim::SpringGeneralizedForce, OpenSim::Thelen2003Muscle, OpenSim::Thelen2003Muscle_Deprecated, OpenSim::TorqueActuator, OpenSim::ZerothOrderMuscleActivationDynamics, OpenSim::Set< ModelComponent, ModelComponent >, OpenSim::AccelerationMotion, OpenSim::DiscreteController, OpenSim::DiscreteForces, OpenSim::AckermannVanDenBogert2010Force, OpenSim::MeyerFregly2016Force, OpenSim::EspositoMiller2018Force, OpenSim::ControlSetController, OpenSim::PrescribedController, OpenSim::ActuatorForceProbe, OpenSim::ActuatorPowerProbe, OpenSim::Bhargava2004MuscleMetabolicsProbe, OpenSim::Bhargava2004SmoothedMuscleMetabolics, OpenSim::Blankevoort1991Ligament, OpenSim::BushingForce, OpenSim::ComponentSet, OpenSim::ConditionalPathPoint, OpenSim::ContactHalfSpace, OpenSim::ContactMesh, OpenSim::ContactSphere, OpenSim::CoordinateLimitForce, OpenSim::ElasticFoundationForce, OpenSim::ElasticFoundationForce, OpenSim::ElasticFoundationForce, OpenSim::ExpressionBasedBushingForce, OpenSim::ExpressionBasedCoordinateForce, OpenSim::ExpressionBasedPointToPointForce, OpenSim::ExternalForce, OpenSim::FunctionBasedBushingForce, OpenSim::GeometryPath, OpenSim::Ground, OpenSim::HuntCrossleyForce, OpenSim::HuntCrossleyForce, OpenSim::HuntCrossleyForce, OpenSim::JointInternalPowerProbe, OpenSim::Ligament, OpenSim::Marker, OpenSim::ModelComponentSet< T >, OpenSim::ModelComponentSet< ModelComponent >, OpenSim::MovingPathPoint, OpenSim::MuscleActiveFiberPowerProbe, OpenSim::PathActuator, OpenSim::PathPoint, OpenSim::PathSpring, OpenSim::PhysicalOffsetFrame, OpenSim::PointToPointSpring, OpenSim::PrescribedForce, OpenSim::SmoothSphereHalfSpaceForce, OpenSim::Station, OpenSim::SystemEnergyProbe, OpenSim::Umberger2010MuscleMetabolicsProbe, OpenSim::ExperimentalFrame, OpenSim::ExperimentalMarker, OpenSim::IMU, OpenSim::PositionMotion, OpenSim::BallJoint, OpenSim::Body, OpenSim::ConstantDistanceConstraint, OpenSim::Coordinate, OpenSim::CoordinateCouplerConstraint, OpenSim::CustomJoint, OpenSim::EllipsoidJoint, OpenSim::FreeJoint, OpenSim::GimbalJoint, OpenSim::PinJoint, OpenSim::PlanarJoint, OpenSim::PointConstraint, OpenSim::PointOnLineConstraint, OpenSim::RollingOnSurfaceConstraint, OpenSim::ScapulothoracicJoint, OpenSim::SliderJoint, OpenSim::UniversalJoint, OpenSim::WeldConstraint, OpenSim::WeldJoint, OpenSim::PathWrapPoint, OpenSim::WrapCylinder, OpenSim::WrapEllipsoid, OpenSim::WrapSphere, OpenSim::WrapTorus, OpenSim::CMC, OpenSim::CorrectionController, OpenSim::MuscleActivationDynamics, OpenSim::StationPlaneContactForce, OpenSim::Controller, OpenSim::AbstractPathPoint, OpenSim::ActivationFiberLengthMuscle, OpenSim::ActivationFiberLengthMuscle_Deprecated, OpenSim::Actuator, OpenSim::ScalarActuator, OpenSim::ContactGeometry, OpenSim::Force, OpenSim::Frame, OpenSim::Muscle, OpenSim::OffsetFrame< C >, OpenSim::OffsetFrame< PhysicalFrame >, OpenSim::PhysicalFrame, OpenSim::Point, OpenSim::Probe, OpenSim::TwoFrameLinker< Force, PhysicalFrame >, OpenSim::TwoFrameLinker< Constraint, PhysicalFrame >, OpenSim::Constraint, OpenSim::Joint, OpenSim::UnilateralConstraint, and OpenSim::WrapObject.
connectToModel()
void OpenSim::ModelComponent::connectToModel (Model & model)
Connect this ModelComponent to its aggregate- a Model.
extendConnectToModel()
virtual void OpenSim::ModelComponent::extendConnectToModel (Model & model) inline protected virtual
Perform any necessary initializations required to connect the component into the Model, and check for error conditions.
extendConnectToModel() is invoked on all components to complete construction of a Model, prior to creating a Simbody System to represent it computationally. It may also be invoked at times just for its error-checking side effects.
If you override this method, be sure to invoke the base class method first, using code like this:
void MyComponent::extendConnectToModel(Model& model) {
    Super::extendConnectToModel(model); // invoke parent class method
    // ... your code goes here
}
Note that this method is expected to check for modeling errors and should throw an OpenSim::Exception if there is something wrong. For example, if your model component references another object by name, you should verify that it exists in the supplied Model, which is not guaranteed since components may be independently instantiated or constructed from XML files.
Parameters
[in,out] model The Model currently being constructed to which this ModelComponent should be connected.
Reimplemented in OpenSim::Delp1990Muscle_Deprecated, OpenSim::UnilateralConstraint, OpenSim::CMC, and OpenSim::CorrectionController.
extendFinalizeFromProperties()
void OpenSim::ModelComponent::extendFinalizeFromProperties () override protected
extendPostScale()
virtual void OpenSim::ModelComponent::extendPostScale (const SimTK::State & s, const ScaleSet & scaleSet) inline protected virtual
Perform any computations that must occur after ModelComponent::scale() has been invoked on all ModelComponents in the Model.
This method is virtual and may be implemented by any subclass of ModelComponent, but all implementations must begin with a call to Super::extendPostScale() to execute the parent class methods before the child class method. The base class implementation in ModelComponent does nothing.
See also
postScale()
Reimplemented in OpenSim::ActivationFiberLengthMuscle_Deprecated.
extendPreScale()
virtual void OpenSim::ModelComponent::extendPreScale (const SimTK::State & s, const ScaleSet & scaleSet) inline protected virtual
Perform any computations that must occur before ModelComponent::scale() is invoked on all ModelComponents in the Model.
For example, a GeometryPath must calculate and store its path length in the original model before scaling so that an owning Muscle can use this information to update the properties of the muscle after scaling. This method is virtual and may be implemented by any subclass of ModelComponent, but all implementations must begin with a call to Super::extendPreScale() to execute the parent class methods before the child class method. The base class implementation in ModelComponent does nothing.
See also
preScale()
extendScale()
virtual void OpenSim::ModelComponent::extendScale (const SimTK::State & s, const ScaleSet & scaleSet) inline protected virtual
Scale the ModelComponent.
This method is virtual and may be implemented by any subclass of ModelComponent, but all implementations must begin with a call to Super::extendScale() to execute the parent class methods before the child class method. The base class implementation in ModelComponent does nothing.
See also
scale()
getClassName()
static const std::string & OpenSim::ModelComponent::getClassName () inline static
This returns "ModelComponent"
See getConcreteClassName() if you want the class name of the underlying concrete object instead.
getConcreteClassName()
const std::string & OpenSim::ModelComponent::getConcreteClassName () const override pure virtual
Returns the class name of the concrete Object-derived class of the actual object referenced by this Object, as a string.
This is the string that is used as the tag for this concrete object in an XML file. Every concrete class derived from Object automatically overrides this method via the declaration macro it uses. See getClassName() to get the class name of the referencing (possibly abstract) class rather than the concrete object.
See also
getClassName()
Implements OpenSim::Component.
Implemented in OpenSim::ActivationCoordinateActuator, OpenSim::BodyActuator, OpenSim::ClutchedPathSpring, OpenSim::ConstantMuscleActivation, OpenSim::CoordinateActuator, OpenSim::DeGrooteFregly2016Muscle, OpenSim::Delp1990Muscle_Deprecated, OpenSim::FirstOrderMuscleActivationDynamics, OpenSim::McKibbenActuator, OpenSim::Millard2012AccelerationMuscle, OpenSim::Millard2012EquilibriumMuscle, OpenSim::MuscleFirstOrderActivationDynamicModel, OpenSim::MuscleFixedWidthPennationModel, OpenSim::PointActuator, OpenSim::PointToPointActuator, OpenSim::RigidTendonMuscle, OpenSim::Schutte1993Muscle_Deprecated, OpenSim::SpringGeneralizedForce, OpenSim::Thelen2003Muscle, OpenSim::Thelen2003Muscle_Deprecated, OpenSim::TorqueActuator, OpenSim::ZerothOrderMuscleActivationDynamics, OpenSim::Set< ModelComponent, ModelComponent >, OpenSim::AccelerationMotion, OpenSim::DiscreteController, OpenSim::DiscreteForces, OpenSim::AckermannVanDenBogert2010Force, OpenSim::MeyerFregly2016Force, OpenSim::EspositoMiller2018Force, OpenSim::ControlSetController, OpenSim::PrescribedController, OpenSim::ActuatorForceProbe, OpenSim::ActuatorPowerProbe, OpenSim::Bhargava2004MuscleMetabolicsProbe, OpenSim::Bhargava2004SmoothedMuscleMetabolics, OpenSim::Blankevoort1991Ligament, OpenSim::BushingForce, OpenSim::ComponentSet, OpenSim::ConditionalPathPoint, OpenSim::ContactHalfSpace, OpenSim::ContactMesh, OpenSim::ContactSphere, OpenSim::CoordinateLimitForce, OpenSim::ElasticFoundationForce, OpenSim::ElasticFoundationForce, OpenSim::ElasticFoundationForce, OpenSim::ExpressionBasedBushingForce, OpenSim::ExpressionBasedCoordinateForce, OpenSim::ExpressionBasedPointToPointForce, OpenSim::ExternalForce, OpenSim::FunctionBasedBushingForce, OpenSim::GeometryPath, OpenSim::Ground, OpenSim::HuntCrossleyForce, OpenSim::HuntCrossleyForce, OpenSim::HuntCrossleyForce, OpenSim::JointInternalPowerProbe, OpenSim::Ligament, OpenSim::Marker, OpenSim::ModelComponentSet< T >, OpenSim::ModelComponentSet< ModelComponent >, OpenSim::MovingPathPoint, OpenSim::MuscleActiveFiberPowerProbe, OpenSim::PathActuator, OpenSim::PathPoint, OpenSim::PathSpring, OpenSim::PhysicalOffsetFrame, OpenSim::PointToPointSpring, OpenSim::PrescribedForce, OpenSim::SmoothSphereHalfSpaceForce, OpenSim::Station, OpenSim::SystemEnergyProbe, OpenSim::Umberger2010MuscleMetabolicsProbe, OpenSim::ExperimentalFrame, OpenSim::ExperimentalMarker, OpenSim::IMU, OpenSim::PositionMotion, OpenSim::BallJoint, OpenSim::Body, OpenSim::ConstantDistanceConstraint, OpenSim::Coordinate, OpenSim::CoordinateCouplerConstraint, OpenSim::CustomJoint, OpenSim::EllipsoidJoint, OpenSim::FreeJoint, OpenSim::GimbalJoint, OpenSim::PinJoint, OpenSim::PlanarJoint, OpenSim::PointConstraint, OpenSim::PointOnLineConstraint, OpenSim::RollingOnSurfaceConstraint, OpenSim::ScapulothoracicJoint, OpenSim::SliderJoint, OpenSim::UniversalJoint, OpenSim::WeldConstraint, OpenSim::WeldJoint, OpenSim::PathWrapPoint, OpenSim::WrapCylinder, OpenSim::WrapEllipsoid, OpenSim::WrapSphere, OpenSim::WrapTorus, OpenSim::CMC, OpenSim::CorrectionController, OpenSim::MuscleActivationDynamics, OpenSim::StationPlaneContactForce, OpenSim::Controller, OpenSim::AbstractPathPoint, OpenSim::ActivationFiberLengthMuscle, OpenSim::ActivationFiberLengthMuscle_Deprecated, OpenSim::Actuator, OpenSim::ScalarActuator, OpenSim::ContactGeometry, OpenSim::Force, OpenSim::Frame, OpenSim::Muscle, OpenSim::OffsetFrame< C >, OpenSim::OffsetFrame< PhysicalFrame >, OpenSim::PhysicalFrame, OpenSim::Point, OpenSim::Probe, OpenSim::TwoFrameLinker< Force, PhysicalFrame >, OpenSim::TwoFrameLinker< Constraint, PhysicalFrame >, OpenSim::Constraint, OpenSim::Joint, OpenSim::UnilateralConstraint, and OpenSim::WrapObject.
getModel()
const Model & OpenSim::ModelComponent::getModel () const
Get a const reference to the Model this component is part of.
Referenced by OpenSim::MocoPhase::getModel().
getScaleFactors()
const SimTK::Vec3 & OpenSim::ModelComponent::getScaleFactors (const ScaleSet & scaleSet, const Frame & frame) const protected
Get the scale factors corresponding to the base OpenSim::Body of the specified Frame.
Returns ModelComponent::InvalidScaleFactors if the ScaleSet does not contain scale factors for the base Body.
hasModel()
bool OpenSim::ModelComponent::hasModel () const inline
Does this ModelComponent have a Model associated with it?
postScale()
void OpenSim::ModelComponent::postScale (const SimTK::State & s, const ScaleSet & scaleSet)
Perform any computations that must occur after ModelComponent::scale() has been invoked on all ModelComponents in the Model.
This method calls the virtual extendPostScale() method, which may be implemented by any subclass of ModelComponent.
See also
preScale()
scale()
extendPostScale()
preScale()
void OpenSim::ModelComponent::preScale (const SimTK::State & s, const ScaleSet & scaleSet)
Perform any computations that must occur before ModelComponent::scale() is invoked on all ModelComponents in the Model.
For example, a GeometryPath must calculate and store its path length in the original model before scaling so that an owning Muscle can use this information to update the properties of the muscle after scaling. This method calls the virtual extendPreScale() method, which may be implemented by any subclass of ModelComponent.
See also
extendPreScale()
scale()
postScale()
safeDownCast()
static ModelComponent * OpenSim::ModelComponent::safeDownCast (OpenSim::Object * obj) inline static
For use in MATLAB and Python to access the concrete class.
Example: cObj = ModelComponent.safeDownCast(obj). This is equivalent to dynamic_cast<ModelComponent*>(obj) in C++.
scale()
void OpenSim::ModelComponent::scale (const SimTK::State & s, const ScaleSet & scaleSet)
Scale the ModelComponent.
This method calls the virtual extendScale() method, which may be implemented by any subclass of ModelComponent.
See also
preScale()
extendScale()
postScale()
updateFromXMLNode()
void OpenSim::ModelComponent::updateFromXMLNode (SimTK::Xml::Element & objectElement, int versionNumber) override protected virtual
Use this method to deserialize an object from a SimTK::Xml::Element.
The element is assumed to be in the format consistent with the passed-in versionNumber. If there is a file attribute in objectElement it will be ignored; if you want it processed you should call readObjectFromXMLNodeOrFile() instead.
Reimplemented from OpenSim::Object.
updModel()
Model & OpenSim::ModelComponent::updModel ()
Get a modifiable reference to the Model this component is part of.
Referenced by OpenSim::MocoPhase::updModel(), and OpenSim::MocoProblem::updModel().
The documentation for this class was generated from the following file:
OpenSim/Simulation/Model/ModelComponent.h