API: OpenSim::Set< T, C > Class Template Reference
OpenSim::Set< T, C > Class Template Reference
A class for holding a set of pointers to objects.
Public Member Functions
virtual ~Set ()
Destructor.
Set ()
Default constructor.
Set (const std::string &aFileName, bool aUpdateFromXMLNode=true)
Construct from file.
Set (const Set< T, C > &aSet)
Copy constructor.
void setupGroups ()
Setup groups (match group member names to set members).
Set< T, C > & operator= (const Set< T, C > &set)
Assign this set to another set.
T & operator[] (int aIndex) const
Get a pointer to the set object at a specified index.
void setMemoryOwner (bool aTrueFalse)
Set whether or not this Set owns the memory pointed to by the pointers it holds.
bool getMemoryOwner () const
Get whether or not this array owns the memory pointed to by the pointers in its array.
bool computeNewCapacity (int aMinCapacity, int &rNewCapacity)
Compute a new capacity that is at least as large as a specified minimum capacity; this method does not change the capacity, it simply computes a new recommended capacity.
bool ensureCapacity (int aCapacity)
Ensure that the capacity of this array is at least the specified amount.
void trim ()
Trim the capacity of this array so that it is one larger than the size of this array.
int getCapacity () const
Get the capacity of this storage instance.
void setCapacityIncrement (int aIncrement)
Set the amount by which the capacity is increased when the capacity of of the array in exceeded.
int getCapacityIncrement () const
Get the amount by which the capacity is increased.
virtual bool setSize (int aSize)
Set the size of the array.
int getSize () const
Get the size of the array.
virtual int getIndex (const T *aObject, int aStartIndex=0) const
Get the index of an object.
virtual int getIndex (const std::string &aName, int aStartIndex=0) const
Get the index of an object by specifying its name.
void getGroupNamesContaining (const std::string &aObjectName, Array< std::string > &rGroupNames) const
Get names of groups containing a given object.
virtual bool adoptAndAppend (T *aObject)
Append to the array, and adopt passed in pointer.
virtual bool cloneAndAppend (const T &aObject)
cloneAndAppend creates a clone of the passed in object and appends the clone to the array.
virtual bool insert (int aIndex, T *aObject)
Insert an object into the array at a specified index.
virtual bool insert (int aIndex, const T &aObject)
Insert an object into the array at a specified index.
virtual bool remove (int aIndex)
Remove an object from the array at a specified index.
virtual bool remove (const T *aObject)
Remove an object from the array by specifying its address.
virtual void clearAndDestroy ()
virtual bool set (int aIndex, T *aObject, bool preserveGroups=false)
Set the object at a specified index.
virtual bool set (int aIndex, const T &aObject, bool preserveGroups=false)
Set the object at a specified index.
virtual T & get (int aIndex) const
Get the value at a specified array index.
T & get (const std::string &aName)
Get the first object that has a specified name.
const T & get (const std::string &aName) const
bool contains (const std::string &aName) const
Get whether this Set contains any object with the specified name.
virtual void getNames (OpenSim::Array< std::string > &rNames) const
Get names of objects in the set.
virtual T * getLast () const
Get the last value in the array.
int searchBinary (const T &aObject, bool aFindFirst=false, int aLo=-1, int aHi=-1) const
Search for the largest value in the array that is less than or equal to a specified value.
int getNumGroups () const
Get the number of groups.
void addGroup (const std::string &aGroupName)
Add an empty group to the set.
void removeGroup (const std::string &aGroupName)
Remove a group from the set.
void renameGroup (const std::string &oldGroupName, const std::string &newGroupName)
Rename a group.
void addObjectToGroup (const std::string &aGroupName, const std::string &aObjectName)
Add an object to a group.
void getGroupNames (Array< std::string > &rGroupNames) const
Get names of all groups.
const ObjectGroup * getGroup (const std::string &aGroupName) const
Get a group by name.
const ObjectGroup * getGroup (int aIndex) const
Get a group by index.
Auto-generated functions
static Set * safeDownCast (OpenSim::Object *obj)
For use in MATLAB and Python to access the concrete class.
static const std::string & getClassName ()
This returns "Set_<T>_".
Set * clone () const override
const std::string & getConcreteClassName () const override
Detailed Description
template<class T, class C = Object>
class OpenSim::Set< T, C >
A class for holding a set of pointers to objects.
It is derived from base class C and is implemented as a wrapper around template class ArrayPtrs<T>.
See also
ArrayPtrs
Author
Frank C. Anderson
Examples:
exampleMarkerTracking.cpp.
Constructor & Destructor Documentation
~Set()
template<class T, class C = Object> virtual OpenSim::Set< T, C >::~Set () inline virtual
Destructor.
Set() [1/3]
template<class T, class C = Object> OpenSim::Set< T, C >::Set () inline
Default constructor.
Set() [2/3]
template<class T, class C = Object> OpenSim::Set< T, C >::Set (const std::string & aFileName, bool aUpdateFromXMLNode = true) inline
Construct from file.
Parameters
aFileName Name of the file.
aUpdateFromXMLNode Whether to update from XML.
Set() [3/3]
template<class T, class C = Object> OpenSim::Set< T, C >::Set (const Set< T, C > & aSet) inline
Copy constructor.
Parameters
aSet Set to be copied.
Member Function Documentation
addGroup()
template<class T, class C = Object> void OpenSim::Set< T, C >::addGroup (const std::string & aGroupName) inline
Add an empty group to the set.
addObjectToGroup()
template<class T, class C = Object> void OpenSim::Set< T, C >::addObjectToGroup (const std::string & aGroupName, const std::string & aObjectName) inline
Add an object to a group.
adoptAndAppend()
template<class T, class C = Object> virtual bool OpenSim::Set< T, C >::adoptAndAppend (T * aObject) inline virtual
Append to the array, and adopt passed in pointer.
A copy is NOT made of the specified object. If getMemoryOwner() is true, this Set takes over ownership of the object and deletes it when the Set itself is deleted.
Parameters
aObject Object to be appended.
Returns
True if the append was successful, false otherwise.
Referenced by OpenSim::ModelScaler::addMeasurement(), OpenSim::ModelScaler::addScale(), and OpenSim::Set< Force, ModelComponent >::cloneAndAppend().
clearAndDestroy()
template<class T, class C = Object> virtual void OpenSim::Set< T, C >::clearAndDestroy () inline virtual
clone()
template<class T, class C = Object> Set* OpenSim::Set< T, C >::clone () const inline override
Reimplemented in OpenSim::ModelComponentSet< ExternalForce >, OpenSim::ModelComponentSet< ContactGeometry >, OpenSim::ModelComponentSet< WrapObject >, OpenSim::ModelComponentSet< Force >, OpenSim::ModelComponentSet< Joint >, OpenSim::ModelComponentSet< Probe >, OpenSim::ModelComponentSet< Controller >, OpenSim::ModelComponentSet< ModelComponent >, OpenSim::ModelComponentSet< Marker >, OpenSim::ModelComponentSet< Body >, and OpenSim::ModelComponentSet< Constraint >.
cloneAndAppend()
template<class T, class C = Object> virtual bool OpenSim::Set< T, C >::cloneAndAppend (const T & aObject) inline virtual
cloneAndAppend creates a clone of the passed in object and appends the clone to the array.
The original object is unaffected and is not associated with the Set. The clone is created using the method clone() available to OpenSim::Object
Parameters
aObject Object whose clone is to be appended.
Returns
True if the append was successful, false otherwise.
Referenced by OpenSim::IKTaskSet::createMarkerWeightSet().
computeNewCapacity()
template<class T, class C = Object> bool OpenSim::Set< T, C >::computeNewCapacity (int aMinCapacity, int & rNewCapacity) inline
Compute a new capacity that is at least as large as a specified minimum capacity; this method does not change the capacity, it simply computes a new recommended capacity.
If the capacity increment is negative, the current capacity is doubled until the computed capacity is greater than or equal to the specified minimum capacity. If the capacity increment is positive, the current capacity increments by this amount until the computed capacity is greater than or equal to the specified minimum capacity. If the capacity increment is zero, the computed capacity is set to the current capacity and false is returned.
Parameters
rNewCapacity New computed capacity.
aMinCapacity Minimum new computed capacity. The computed capacity is incremented until it is at least as large as aMinCapacity, assuming the capacity increment is not zero.
Returns
True if the new capacity was increased, false otherwise (i.e., if the capacity increment is set to 0).
See also
setCapacityIncrement()
contains()
template<class T, class C = Object> bool OpenSim::Set< T, C >::contains (const std::string & aName) const inline
Get whether this Set contains any object with the specified name.
Parameters
aName Name of the desired object.
Returns
true if the object exists
Referenced by OpenSim::Set< Force, ModelComponent >::getGroupNamesContaining().
ensureCapacity()
template<class T, class C = Object> bool OpenSim::Set< T, C >::ensureCapacity (int aCapacity) inline
Ensure that the capacity of this array is at least the specified amount.
The newly allocated array elements are initialized to NULL.
Parameters
aCapacity Desired capacity.
Returns
true if the capacity was successfully obtained, false otherwise.
get() [1/3]
template<class T, class C = Object> virtual T& OpenSim::Set< T, C >::get (int aIndex) const inline virtual
Get the value at a specified array index.
If the index is negative or passed the end of the array, an exception is thrown.
For faster execution, the array elements can be accessed through the overloaded operator[], which does no bounds checking.
Parameters
aIndex Index of the desired array element.
Returns
Reference to the array element.
Exceptions
Exception if (aIndex<0)||(aIndex>=_size) or if the pointer at aIndex is NULL.
See also
operator[].
get() [2/3]
template<class T, class C = Object> T& OpenSim::Set< T, C >::get (const std::string & aName) inline
Get the first object that has a specified name.
If the array doesn't contain an object of the specified name, an exception is thrown.
Parameters
aName Name of the desired object.
Returns
Pointer to the object.
Exceptions
Exception if no such object exists.
See also
getIndex()
get() [3/3]
template<class T, class C = Object> const T& OpenSim::Set< T, C >::get (const std::string & aName) const inline
getCapacity()
template<class T, class C = Object> int OpenSim::Set< T, C >::getCapacity () const inline
Get the capacity of this storage instance.
getCapacityIncrement()
template<class T, class C = Object> int OpenSim::Set< T, C >::getCapacityIncrement () const inline
Get the amount by which the capacity is increased.
getClassName()
template<class T, class C = Object> static const std::string& OpenSim::Set< T, C >::getClassName () inline static
This returns "Set_<T>_".
T is the template argument for this class. See getConcreteClassName() if you want the class name of the underlying concrete object instead.
getConcreteClassName()
template<class T, class C = Object> const std::string& OpenSim::Set< T, C >::getConcreteClassName () const inline override
Reimplemented in OpenSim::ModelComponentSet< ExternalForce >, OpenSim::ModelComponentSet< ContactGeometry >, OpenSim::ModelComponentSet< WrapObject >, OpenSim::ModelComponentSet< Force >, OpenSim::ModelComponentSet< Joint >, OpenSim::ModelComponentSet< Probe >, OpenSim::ModelComponentSet< Controller >, OpenSim::ModelComponentSet< ModelComponent >, OpenSim::ModelComponentSet< Marker >, OpenSim::ModelComponentSet< Body >, and OpenSim::ModelComponentSet< Constraint >.
getGroup() [1/2]
template<class T, class C = Object> const ObjectGroup* OpenSim::Set< T, C >::getGroup (const std::string & aGroupName) const inline
Get a group by name.
getGroup() [2/2]
template<class T, class C = Object> const ObjectGroup* OpenSim::Set< T, C >::getGroup (int aIndex) const inline
Get a group by index.
getGroupNames()
template<class T, class C = Object> void OpenSim::Set< T, C >::getGroupNames (Array< std::string > & rGroupNames) const inline
Get names of all groups.
getGroupNamesContaining()
template<class T, class C = Object> void OpenSim::Set< T, C >::getGroupNamesContaining (const std::string & aObjectName, Array< std::string > & rGroupNames) const inline
Get names of groups containing a given object.
getIndex() [1/2]
template<class T, class C = Object> virtual int OpenSim::Set< T, C >::getIndex (const T * aObject, int aStartIndex = 0) const inline virtual
Get the index of an object.
Parameters
aObject Address of the object whose index is sought.
aStartIndex Index at which to start searching. If the object is not found at or following aStartIndex, the array is searched from its beginning.
Returns
Index of the object with the address aObject. If no such object exists in the array, -1 is returned.
getIndex() [2/2]
template<class T, class C = Object> virtual int OpenSim::Set< T, C >::getIndex (const std::string & aName, int aStartIndex = 0) const inline virtual
Get the index of an object by specifying its name.
Parameters
aName Name of the object whose index is sought.
aStartIndex Index at which to start searching. If the object is not found at or following aStartIndex, the array is searched from its beginning.
Returns
Index of the object named aName. If no such object exists in the array, -1 is returned.
getLast()
template<class T, class C = Object> virtual T* OpenSim::Set< T, C >::getLast () const inline virtual
Get the last value in the array.
Returns
Last value in the array.
Exceptions
Exception if the array is empty.
getMemoryOwner()
template<class T, class C = Object> bool OpenSim::Set< T, C >::getMemoryOwner () const inline
Get whether or not this array owns the memory pointed to by the pointers in its array.
If the array is set to own the memory pointed to by its pointers, this array issues deletes for all these pointers upon the array's destruction. If not, this array does not issue deletes.
Returns
True if this array owns the memory; false otherwise.
getNames()
template<class T, class C = Object> virtual void OpenSim::Set< T, C >::getNames (OpenSim::Array< std::string > & rNames) const inline virtual
Get names of objects in the set.
Parameters
rNames Array of names. The names are appended to rNames, so it is permissible to send in an non-empty array; the names in the set will simply be appended to the array sent in.
getNumGroups()
template<class T, class C = Object> int OpenSim::Set< T, C >::getNumGroups () const inline
Get the number of groups.
getSize()
template<class T, class C = Object> int OpenSim::Set< T, C >::getSize () const inline
Get the size of the array.
Returns
Size of the array.
Referenced by OpenSim::ProbeReporter::disableIntegrationOnlyProbes(), OpenSim::Measurement::getNumMarkerPairs(), and OpenSim::StateTrackingTask::getTaskErrorGradient().
insert() [1/2]
template<class T, class C = Object> virtual bool OpenSim::Set< T, C >::insert (int aIndex, T * aObject) inline virtual
Insert an object into the array at a specified index.
A copy of the specified object is NOT made. If getMemoryOwner() is true, this Set takes over ownership of the object and deletes it when the Set itself is deleted.
This method is relatively computationally costly since many of the array elements may need to be shifted.
Parameters
aObject Object to be inserted.
aIndex Index at which to insert the new object. All current elements from aIndex to the end of the array are shifted one place in the direction of the end of the array. The specified index must be less than or equal to the size of the array. Note that if aIndex is equal to the size of the array, the insertion is equivalent to an append.
Returns
True if the insertion was successful, false otherwise.
Reimplemented in OpenSim::ForceSet.
Referenced by OpenSim::Set< Force, ModelComponent >::insert().
insert() [2/2]
template<class T, class C = Object> virtual bool OpenSim::Set< T, C >::insert (int aIndex, const T & aObject) inline virtual
Insert an object into the array at a specified index.
A copy is made of the object and added to the Set. The original object is unaffected.
This method is relatively computationally costly since many of the array elements may need to be shifted.
Parameters
aObject Object to be inserted.
aIndex Index at which to insert the new object. All current elements from aIndex to the end of the array are shifted one place in the direction of the end of the array. The specified index must be less than or equal to the size of the array. Note that if aIndex is equal to the size of the array, the insertion is equivalent to an append.
Returns
True if the insertion was successful, false otherwise.
operator=()
template<class T, class C = Object> Set<T,C>& OpenSim::Set< T, C >::operator= (const Set< T, C > & set) inline
Assign this set to another set.
This operator makes a complete copy of the specified set; all member variables and objects in the set are copied. Because all objects are copied, this set takes ownership of the newly allocated objects (i.e., _memoryOwner is set to true. So, the result is two independent, identical sets, with the possible exception of the _memoryOwner flag.
Parameters
set The Set to be copied.
Returns
Reference to this set.
Referenced by OpenSim::IKTaskSet::operator=().
operator[]()
template<class T, class C = Object> T& OpenSim::Set< T, C >::operator[] (int aIndex) const inline
Get a pointer to the set object at a specified index.
This operator is intended for accessing set objects with as little overhead as possible, so no error checking is performed. The caller must make sure the specified index is within the bounds of the array. If error checking is desired, use ArrayPtrs::get().
Parameters
aIndex Index of the desired element (0 <= aIndex < _size).
Returns
Reference to the array element.
Exceptions
Exception if a NULL pointer is encountered.
See also
get().
remove() [1/2]
template<class T, class C = Object> virtual bool OpenSim::Set< T, C >::remove (int aIndex) inline virtual
Remove an object from the array at a specified index.
If this set is set as the memory owner, the object is deleted when it is removed.
This method is relatively computationally costly since many of the array elements may need to be shifted.
Parameters
aIndex Index of the value to remove. All elements from aIndex to the end of the array are shifted one place toward the beginning of the array. If aIndex is less than 0 or greater than or equal to the current size of the array, no element is removed.
Returns
True if the removal was successful, false otherwise.
Reimplemented in OpenSim::ForceSet.
remove() [2/2]
template<class T, class C = Object> virtual bool OpenSim::Set< T, C >::remove (const T * aObject) inline virtual
Remove an object from the array by specifying its address.
The object is deleted when it is removed.
This method is relatively computationally costly since many of the array elements may need to be shifted.
Parameters
aObject Pointer to the object to be removed. If an object with the specified address is not found, no action is taken.
Returns
True if the removal was successful, false otherwise.
removeGroup()
template<class T, class C = Object> void OpenSim::Set< T, C >::removeGroup (const std::string & aGroupName) inline
Remove a group from the set.
Elements are not removed.
renameGroup()
template<class T, class C = Object> void OpenSim::Set< T, C >::renameGroup (const std::string & oldGroupName, const std::string & newGroupName) inline
Rename a group.
safeDownCast()
template<class T, class C = Object> static Set* OpenSim::Set< T, C >::safeDownCast (OpenSim::Object * obj) inline static
For use in MATLAB and Python to access the concrete class.
Example: cObj = Set.safeDownCast(obj). This is equivalent to dynamic_cast<Set*>(obj) in C++.
searchBinary()
template<class T, class C = Object> int OpenSim::Set< T, C >::searchBinary (const T & aObject, bool aFindFirst = false, int aLo = -1, int aHi = -1) const inline
Search for the largest value in the array that is less than or equal to a specified value.
If there is more than one element with this largest value, the index of the first of these elements can optionally be found, but this can be up to twice as costly.
This method assumes that the array element values monotonically increase as the array index increases. Note that monotonically increase means never decrease, so it is permissible for adjacent elements to have the same value.
A binary search is performed (i.e., the array is repeatedly subdivided into two bins one of which must contain the specified until the appropriate element is identified), so the performance of this method is approximately ln(n), where n is the size of the array.
Parameters
aObject Value to which the array elements are compared.
aFindFirst If true, find the first element that satisfies the search. If false, the index of any element that satisfies the search can be returned- which index will be returned depends on the length of the array and is therefore somewhat arbitrary. By default, this flag is false.
aLo Lowest array index to consider in the search.
aHi Highest array index to consider in the search.
Returns
Index of the array element that has the largest value that is less than or equal to aValue. If there is more than one such elements with the same value and aFindFirst is set to true, the index of the first of these elements is returned. If an error is encountered (e.g., the array is empty), or the array contains no element that is less than or equal to aValue, -1 is returned.
set() [1/2]
template<class T, class C = Object> virtual bool OpenSim::Set< T, C >::set (int aIndex, T * aObject, bool preserveGroups = false) inline virtual
Set the object at a specified index.
A copy of the object is NOT made. If getMemoryOwner() is true, this Set takes over ownership of the object and deletes it when the Set itself is deleted.
Parameters
aIndex Index of the array element to be set. aIndex must be greater than zero and less than or equal to the size of the array. Note that if aIndex is equal to the size of the array, the set is equivalent to an append.
aObject Object to be set.
preserveGroups If true, the new object will be added to the groups that the object it replaces belonged to
Returns
True if the set was successful, false otherwise.
Reimplemented in OpenSim::ForceSet.
set() [2/2]
template<class T, class C = Object> virtual bool OpenSim::Set< T, C >::set (int aIndex, const T & aObject, bool preserveGroups = false) inline virtual
Set the object at a specified index.
A copy is made of the object and added to the Set. The original object is unaffected.
Parameters
aIndex Index of the array element to be set. aIndex must be greater than zero and less than or equal to the size of the array. Note that if aIndex is equal to the size of the array, the set is equivalent to an append.
aObject Object to be set.
preserveGroups If true, the new object will be added to the groups that the object it replaces belonged to
Returns
True if the set was successful, false otherwise.
setCapacityIncrement()
template<class T, class C = Object> void OpenSim::Set< T, C >::setCapacityIncrement (int aIncrement) inline
Set the amount by which the capacity is increased when the capacity of of the array in exceeded.
If the specified increment is negative or this method is called with no argument, the capacity is set to double whenever the capacity is exceeded.
Parameters
aIncrement Desired capacity increment.
setMemoryOwner()
template<class T, class C = Object> void OpenSim::Set< T, C >::setMemoryOwner (bool aTrueFalse) inline
Set whether or not this Set owns the memory pointed to by the pointers it holds.
Parameters
aTrueFalse If true, all the memory associated with each of the pointers in this array are deleted upon the array's destruction. If false, deletes are not issued for each of the pointers.
setSize()
template<class T, class C = Object> virtual bool OpenSim::Set< T, C >::setSize (int aSize) inline virtual
Set the size of the array.
This method can be used only to decrease the size of the array. If the size of an array is decreased, all objects in the array that become invalid as a result of the decrease are deleted.
Note that the size of an array is different than its capacity. The size indicates how many valid elements are stored in an array. The capacity indicates how much the size of the array can be increased without allocated more memory. At all times size <= capacity.
Parameters
aSize Desired size of the array. The size must be greater than or equal to zero and less than or equal to the current size of the array.
Returns
True if the requested size change was carried out, false otherwise.
setupGroups()
template<class T, class C = Object> void OpenSim::Set< T, C >::setupGroups () inline
Setup groups (match group member names to set members).
trim()
template<class T, class C = Object> void OpenSim::Set< T, C >::trim () inline
Trim the capacity of this array so that it is one larger than the size of this array.
This is useful for reducing the amount of memory used by this array. This capacity is kept at one larger than the size so that, for example, an array of characters can be treated as a NULL terminated string.
The documentation for this class was generated from the following file:
OpenSim/Common/Set.h