API: OpenSim::ControlLinear Class Reference
OpenSim::ControlLinear Class Reference
A class that represents a piece-wise linear control curve.
Public Member Functions
ControlLinear ()
ControlLinear (const ControlLinear &aControl)
virtual ~ControlLinear ()
void copyData (const ControlLinear &aControl)
Copy the member variables of the specified ControlLinear over to this ControlLinear.
ControlLinear & operator= (const ControlLinear &aControl)
void setUseSteps (bool aTrueFalse)
Sets whether or not step functions are used between control nodes or linear interpolation.
bool getUseSteps () const
void setKp (double aKp)
Sets the position gain for PD follower filter.
double getKp () const
void setKv (double aKv)
Sets the velocity gain for PD follower filter.
double getKv () const
int getNumParameters () const override
Returns the number of parameters that are used to specify the control curve.
void setParameterMin (int aI, double aMin) override
Sets the minimum value that a control parameter can take on.
double getParameterMin (int aI) const override
void setParameterMax (int aI, double aMax) override
Set the maximum value that a control parameter can take on.
double getParameterMax (int aI) const override
double getParameterTime (int aI) const override
Get the time at which a parameter (control curve value) is specified.
void getParameterNeighborhood (int aI, double &rTLower, double &rTUpper) const override
int getParameterList (double aT, Array< int > &rList) override
int getParameterList (double aT1, double aT2, Array< int > &rList) override
Gets the list of parameters that affect the control curve between two specified times and that do NOT affect the control curve below the lower of these two times.
void setParameterValue (int aI, double aP) override
double getParameterValue (int aI) const override
void setControlValue (double aT, double aX) override
This method adds a set of control parameters at the specified time unless the specified time equals the time of an existing ControlLinearNode, in which case the parameters of that control node are changed.
double getControlValue (double aT) override
Gets the value of this control at time aT.
double getControlValueMin (double aT=0.0) override
Gets the minimum allowed value of this control at time aT.
void setControlValueMin (double aT, double aX) override
This method adds a set of control parameters at the specified time unless the specified time equals the time of an existing control node, in which case the parameters of that control node are changed.
double getControlValueMax (double aT=0.0) override
Gets the maximum allowed value of this control at time aT.
void setControlValueMax (double aT, double aX) override
This method adds a set of control parameters at the specified time unless the specified time equals the time of an existing control node, in which case the parameters of that control node are changed.
void clearControlNodes ()
ArrayPtrs< ControlLinearNode > & getControlValues ()
ArrayPtrs< ControlLinearNode > & getControlMinValues ()
ArrayPtrs< ControlLinearNode > & getControlMaxValues ()
void insertNewValueNode (int index, const ControlLinearNode &newNode)
Called from GUI to work around early garbage collection.
void insertNewMinNode (int index, const ControlLinearNode &newNode)
Called from GUI to work around early garbage collection.
void insertNewMaxNode (int index, const ControlLinearNode &newNode)
Called from GUI to work around early garbage collection.
double getFirstTime () const override
The time corresponding to the first ControlLinearNode.
double getLastTime () const override
The time corresponding to the last ControlLinearNode.
void simplify (const PropertySet &aProperties) override
The number of control nodes is reduced by first applying a lowpass filter to the sequence of control nodes using a specified cutoff frequency and then removing nodes that keep the curve within a specified distance to the low-pass filtered curve.
bool simplify (const double &cutoffFrequency, const double &distance)
Another interface to simplify that: (1) does not require properties, and (2) returns bool on failure for a more graceful batch simplification.
void filter (double aT) override
Filter the control curve at a particular time using a PD follower filter.
Public Member Functions inherited from OpenSim::Control
Control (const char *aName="UNKNOWN")
Control (const Control &aControl)
virtual ~Control ()
Control & operator= (const Control &aControl)
void setIsModelControl (bool aTrueFalse)
Sets whether or not this control is a model control.
bool getIsModelControl () const
void setExtrapolate (bool aTrueFalse)
Sets whether or not to extrapolate for control curve evaluations that are outside the region of confidence for a control.
bool getExtrapolate () const
void setFilterOn (bool aTrueFalse)
Sets whether or not to apply a PD (proportional-derivative) filter to the control values.
bool getFilterOn () const
void setDefaultParameterMin (double aMin)
Sets the default minimum value of a control parameter.
double getDefaultParameterMin () const
void setDefaultParameterMax (double aMax)
Sets the default maximum value of a control parameter.
double getDefaultParameterMax () const
Public Member Functions inherited from OpenSim::Object
virtual ~Object ()
Virtual destructor for cleanup.
bool isEqualTo (const Object &aObject) const
Equality operator wrapper for use from languages not supporting operator overloading.
Object & operator= (const Object &aObject)
Copy assignment copies he base class fields, including the properties.
virtual bool operator== (const Object &aObject) const
Determine if two objects are equal.
virtual bool operator< (const Object &aObject) const
Provide an ordering for objects so they can be put in sorted containers.
void setName (const std::string &name)
Set the name of the Object.
const std::string & getName () const
Get the name of this Object.
void setDescription (const std::string &description)
Set description, a one-liner summary.
const std::string & getDescription () const
Get description, a one-liner summary.
const std::string & getAuthors () const
Get Authors of this Object.
void setAuthors (const std::string &authors)
Set Authors of this object.
const std::string & getReferences () const
Get references or publications to cite if using this object.
void setReferences (const std::string &references)
Set references or publications to cite if using this object.
int getNumProperties () const
Determine how many properties are stored with this Object.
const AbstractProperty & getPropertyByIndex (int propertyIndex) const
Get a const reference to a property by its index number, returned as an AbstractProperty.
AbstractProperty & updPropertyByIndex (int propertyIndex)
Get a writable reference to a property by its index number, returned as an AbstractProperty.
bool hasProperty (const std::string &name) const
Return true if this Object has a property of any type with the given name, which must not be empty.
const AbstractProperty & getPropertyByName (const std::string &name) const
Get a const reference to a property by its name, returned as an AbstractProperty.
AbstractProperty & updPropertyByName (const std::string &name)
Get a writable reference to a property by its name, returned as an AbstractProperty.
template<class T >
bool hasProperty () const
Return true if this Object contains an unnamed, one-object property that contains objects of the given template type T.
template<class T >
const Property< T > & getProperty (const PropertyIndex &index) const
Get property of known type Property<T> as a const reference; the property must be present and have the right type.
template<class T >
Property< T > & updProperty (const PropertyIndex &index)
Get property of known type Property<T> as a writable reference; the property must be present and have the right type.
bool isObjectUpToDateWithProperties () const
Returns true if no property's value has changed since the last time setObjectIsUpToDateWithProperties() was called.
void readObjectFromXMLNodeOrFile (SimTK::Xml::Element &objectElement, int versionNumber)
We're given an XML element from which we are to populate this Object.
virtual void updateFromXMLNode (SimTK::Xml::Element &objectElement, int versionNumber)
Use this method to deserialize an object from a SimTK::Xml::Element.
void updateXMLNode (SimTK::Xml::Element &parent, const AbstractProperty *prop=nullptr) const
Serialize this object into the XML node that represents it.
bool getInlined () const
Inlined means an in-memory Object that is not associated with an XMLDocument.
void setInlined (bool aInlined, const std::string &aFileName="")
Mark this as inlined or not and optionally provide a file name to associate with the new XMLDocument for the non-inline case.
std::string getDocumentFileName () const
If there is a document associated with this object then return the file name maintained by the document.
int getDocumentFileVersion () const
If there is a document associated with this object then return its version number.
void setAllPropertiesUseDefault (bool aUseDefault)
bool print (const std::string &fileName) const
Write this Object into an XML file of the given name; conventionally the suffix to use is ".osim".
std::string dump () const
dump the XML representation of this Object into an std::string and return it.
virtual bool isA (const char *type) const
The default implementation returns true only if the supplied string is "Object"; each Object-derived class overrides this to match its own class name.
const std::string & toString () const
Wrapper to be used on Java side to display objects in tree; this returns just the object's name.
PropertySet & getPropertySet ()
OBSOLETE: Get a reference to the PropertySet maintained by the Object.
const PropertySet & getPropertySet () const
Static Public Member Functions
static double Interpolate (double aX1, double aY1, double aX2, double aY2, double aX)
Linearly interpolate or extrapolate given two points.
Static Public Member Functions inherited from OpenSim::Control
static Control * safeDownCast (OpenSim::Object *obj)
For use in MATLAB and Python to access the concrete class.
static const std::string & getClassName ()
This returns "Control".
Static Public Member Functions inherited from OpenSim::Object
static void registerType (const Object &defaultObject)
Register an instance of a class; if the class is already registered it will be replaced.
static void renameType (const std::string &oldTypeName, const std::string &newTypeName)
Support versioning by associating the current Object type with an old name.
static const Object * getDefaultInstanceOfType (const std::string &concreteClassName)
Return a pointer to the default instance of the registered (concrete) Object whose class name is given, or NULL if the type is not registered.
template<class T >
static bool isObjectTypeDerivedFrom (const std::string &concreteClassName)
Return true if the given concrete object type represents a subclass of the template object type T, and thus could be referenced with a T*.
static Object * newInstanceOfType (const std::string &concreteClassName)
Create a new instance of the concrete Object type whose class name is given as concreteClassName.
static void getRegisteredTypenames (Array< std::string > &typeNames)
Retrieve all the typenames registered so far.
template<class T >
static void getRegisteredObjectsOfGivenType (ArrayPtrs< T > &rArray)
Return an array of pointers to the default instances of all registered (concrete) Object types that derive from a given Object-derived type that does not have to be concrete.
static bool PrintPropertyInfo (std::ostream &os, const std::string &classNameDotPropertyName, bool printFlagInfo=true)
Dump formatted property information to a given output stream, useful for creating a "help" facility for registered objects.
static bool PrintPropertyInfo (std::ostream &os, const std::string &className, const std::string &propertyName, bool printFlagInfo=true)
Same as the other signature but the class name and property name are provided as two separate strings.
static Object * makeObjectFromFile (const std::string &fileName)
Create an OpenSim object whose type is based on the tag at the root node of the XML file passed in.
static const std::string & getClassName ()
Return the name of this class as a string; i.e., "Object".
static void setSerializeAllDefaults (bool shouldSerializeDefaults)
Static function to control whether all registered objects and their properties are written to the defaults section of output files rather than only those values for which the default was explicitly overwritten when read in from an input file or set programmatically.
static bool getSerializeAllDefaults ()
Report the value of the "serialize all defaults" flag.
static bool isKindOf (const char *type)
Returns true if the passed-in string is "Object"; each Object-derived class defines a method of this name for its own class name.
static void setDebugLevel (int newLevel)
Set the amount of logging output.
static int getDebugLevel ()
Get the current setting of debug level.
static Object * SafeCopy (const Object *aObject)
Use the clone() method to duplicate the given object unless the pointer is null in which case null is returned.
static void RegisterType (const Object &defaultObject)
OBSOLETE alternate name for registerType().
static void RenameType (const std::string &oldName, const std::string &newName)
OBSOLETE alternate name for renameType().
Auto-generated functions
static ControlLinear * safeDownCast (OpenSim::Object *obj)
For use in MATLAB and Python to access the concrete class.
static const std::string & getClassName ()
This returns "ControlLinear".
ControlLinear * clone () const override
Create a new heap-allocated copy of the concrete object to which this Object refers.
const std::string & getConcreteClassName () const override
Returns the class name of the concrete Object-derived class of the actual object referenced by this Object, as a string.
Detailed Description
A class that represents a piece-wise linear control curve.
The curve is specified by an array of control nodes (see class ControlLinearNode) that occur at monotonically increasing times. The value of the control curve is computed by linearly interpolating the values of the appropriate control nodes.
For this Control, parameters are the values of the ControlLinearNode's.
Author
Frank C. Anderson
Version
1.0
Constructor & Destructor Documentation
ControlLinear() [1/2]
OpenSim::ControlLinear::ControlLinear ()
ControlLinear() [2/2]
OpenSim::ControlLinear::ControlLinear (const ControlLinear & aControl)
~ControlLinear()
virtual OpenSim::ControlLinear::~ControlLinear () virtual
Member Function Documentation
clearControlNodes()
void OpenSim::ControlLinear::clearControlNodes ()
clone()
ControlLinear* OpenSim::ControlLinear::clone () const inline override virtual
Create a new heap-allocated copy of the concrete object to which this Object refers.
It is up to the caller to delete the returned object when no longer needed. Every concrete object deriving from Object implements this pure virtual method automatically, via the declaration macro it invokes (e.g., OpenSim_DECLARE_CONCRETE_OBJECT()). Note that the concrete class overrides modify the return type to be a pointer to the concrete object; that still overrides the base class method because the return type is covariant with (that is, derives from) Object.
Implements OpenSim::Control.
copyData()
void OpenSim::ControlLinear::copyData (const ControlLinear & aControl)
Copy the member variables of the specified ControlLinear over to this ControlLinear.
filter()
void OpenSim::ControlLinear::filter (double aT) override virtual
Filter the control curve at a particular time using a PD follower filter.
See also
setFilterOn()
Parameters
aT Time at which to compute a new, filtered control value
Reimplemented from OpenSim::Control.
getClassName()
static const std::string& OpenSim::ControlLinear::getClassName () inline static
This returns "ControlLinear".
See getConcreteClassName() if you want the class name of the underlying concrete object instead.
getConcreteClassName()
const std::string& OpenSim::ControlLinear::getConcreteClassName () const inline override virtual
Returns the class name of the concrete Object-derived class of the actual object referenced by this Object, as a string.
This is the string that is used as the tag for this concrete object in an XML file. Every concrete class derived from Object automatically overrides this method via the declaration macro it uses. See getClassName() to get the class name of the referencing (possibly abstract) class rather than the concrete object.
See also
getClassName()
Implements OpenSim::Control.
getControlMaxValues()
ArrayPtrs<ControlLinearNode>& OpenSim::ControlLinear::getControlMaxValues () inline
getControlMinValues()
ArrayPtrs<ControlLinearNode>& OpenSim::ControlLinear::getControlMinValues () inline
getControlValue()
double OpenSim::ControlLinear::getControlValue (double aT) override virtual
Gets the value of this control at time aT.
If the value of the curve is not defined, SimTK::NaN is returned. If the control is set to extrapolate, (see getExtrapolate()), and the time is before that of the first node or after that of the last node, then an extrapolation is performed to determine the value of the control curve. Otherwise, the value of either the first control node or last control node is returned.
Parameters
aT Time at which to get the control.
Implements OpenSim::Control.
getControlValueMax()
double OpenSim::ControlLinear::getControlValueMax (double aT = 0.0) override virtual
Gets the maximum allowed value of this control at time aT.
Parameters
aT Time at which to get the control.
Returns
Maximum allowed control value. If the value of the curve is not defined, _defaultMax is returned. If the control is set to extrapolate, getExtraplate, and the time is before the first node or after the last node, then an extrapolation is performed to determine the value of the control curve. Otherwise, the value of either the first control node or last control node is returned.
Implements OpenSim::Control.
getControlValueMin()
double OpenSim::ControlLinear::getControlValueMin (double aT = 0.0) override virtual
Gets the minimum allowed value of this control at time aT.
Parameters
aT Time at which to get the control.
Returns
Minimum allowed control value. If the value of the curve is not defined, _defaultMin is returned. If the control is set to extrapolate, (see getExtraplate()), and the time is before the first node or after the last node, then an extrapolation is performed to determine the value of the control curve. Otherwise, the value of either the first control node or last control node is returned.
Implements OpenSim::Control.
getControlValues()
ArrayPtrs<ControlLinearNode>& OpenSim::ControlLinear::getControlValues () inline
getFirstTime()
double OpenSim::ControlLinear::getFirstTime () const override virtual
The time corresponding to the first ControlLinearNode.
Reimplemented from OpenSim::Control.
getKp()
double OpenSim::ControlLinear::getKp () const
See also
setKp()
getKv()
double OpenSim::ControlLinear::getKv () const
See also
setKv()
getLastTime()
double OpenSim::ControlLinear::getLastTime () const override virtual
The time corresponding to the last ControlLinearNode.
Reimplemented from OpenSim::Control.
getNumParameters()
int OpenSim::ControlLinear::getNumParameters () const override virtual
Returns the number of parameters that are used to specify the control curve.
Implements OpenSim::Control.
getParameterList() [1/2]
int OpenSim::ControlLinear::getParameterList (double aT, Array< int > & rList) override virtual
Parameters
aT time
rList If aT lies between two nodes, the indices of these two nodes are returned; if aT equals the time at which a node occurs, the index of that node is returned; if aT is less than the time of the first node in the array, the index of the first node (i.e., 0) is returned; if aT is greater than the time of the last node, the index of the last node (i.e., size-1) is returned.
Implements OpenSim::Control.
getParameterList() [2/2]
int OpenSim::ControlLinear::getParameterList (double aTLower, double aTUpper, Array< int > & rList) override virtual
Gets the list of parameters that affect the control curve between two specified times and that do NOT affect the control curve below the lower of these two times.
This method is useful when solving for a set of controls for a dynamic simulation. When solving for a set of controls, one always wants to go forward in time. Therefore, one does not want to change control parameters that affect the control curve at past times.
A control parameter is included in the list only if it affects the control curve in the specified time interval AND does NOT affect the control curve below the lower bound of the specified time interval. So, it is possible that some of the parameters on the returned list could affect the control curve at times greater than the upper bound of the specified time interval.
Parameters
aTLower Lower time bound.
aTUpper Upper time bound.
rList List of indices of the control parameters that affect the curve between aTLower and aTUpper but not before aTLower.
Returns
Length of rList.
Implements OpenSim::Control.
getParameterMax()
double OpenSim::ControlLinear::getParameterMax (int aI) const override virtual
See also
setParameterMax()
Parameters
aI Index of the parameter.
Exceptions
Exception if aI is invalid.
Implements OpenSim::Control.
getParameterMin()
double OpenSim::ControlLinear::getParameterMin (int aI) const override virtual
See also
setParameterMin()
Parameters
aI Index of the parameter for which the minimum value is desired.
Exceptions
Exception if aI is invalid.
Implements OpenSim::Control.
getParameterNeighborhood()
void OpenSim::ControlLinear::getParameterNeighborhood (int aI, double & rTLower, double & rTUpper) const override virtual
Parameters
aI Index of the parameter.
rTLower The time of parameter aI-1 or of aI if there is no parameter aI-1. If there are no ControlLinearNode's at all or if aI is invalid, rTLower is given the value SimTK::NaN.
rTUpper The time of parameter aI+1 or of aI if there is no parameter aI+1. If there are no ControlLinearNode's at all or if aI is invalid, rTUpper is given the value SimTK::NaN.
Implements OpenSim::Control.
getParameterTime()
double OpenSim::ControlLinear::getParameterTime (int aI) const override virtual
Get the time at which a parameter (control curve value) is specified.
Not for minimum or maximum values of parameters; only for specified values of the control curve, as set via setParameterValue() or setControlValue().
Parameters
aI Index of the parameter.
Exceptions
Exception if aI is invalid.
Implements OpenSim::Control.
getParameterValue()
double OpenSim::ControlLinear::getParameterValue (int aI) const override virtual
See also
setParameterValue()
Implements OpenSim::Control.
getUseSteps()
bool OpenSim::ControlLinear::getUseSteps () const
See also
setUseSteps()
insertNewMaxNode()
void OpenSim::ControlLinear::insertNewMaxNode (int index, const ControlLinearNode & newNode) inline
Called from GUI to work around early garbage collection.
References OpenSim::ControlLinearNode::clone().
insertNewMinNode()
void OpenSim::ControlLinear::insertNewMinNode (int index, const ControlLinearNode & newNode) inline
Called from GUI to work around early garbage collection.
References OpenSim::ControlLinearNode::clone().
insertNewValueNode()
void OpenSim::ControlLinear::insertNewValueNode (int index, const ControlLinearNode & newNode) inline
Called from GUI to work around early garbage collection.
References OpenSim::ControlLinearNode::clone().
Interpolate()
static double OpenSim::ControlLinear::Interpolate (double aX1, double aY1, double aX2, double aY2, double aX) static
Linearly interpolate or extrapolate given two points.
Parameters
aX1 X coordinate of point 1.
aY1 Y coordinate of point 1.
aX2 X coordinate of point 2.
aY2 Y coordinate of point 2.
aX X coordinate whose corresponding Y coordinate is desired.
Returns
Y value corresponding to aX.
operator=()
ControlLinear& OpenSim::ControlLinear::operator= (const ControlLinear & aControl)
safeDownCast()
static ControlLinear* OpenSim::ControlLinear::safeDownCast (OpenSim::Object * obj) inline static
For use in MATLAB and Python to access the concrete class.
Example: cObj = ControlLinear.safeDownCast(obj). This is equivalent to dynamic_cast<ControlLinear*>(obj) in C++.
setControlValue()
void OpenSim::ControlLinear::setControlValue (double aT, double aX) override virtual
This method adds a set of control parameters at the specified time unless the specified time equals the time of an existing ControlLinearNode, in which case the parameters of that control node are changed.
Implements OpenSim::Control.
setControlValueMax()
void OpenSim::ControlLinear::setControlValueMax (double aT, double aX) override virtual
This method adds a set of control parameters at the specified time unless the specified time equals the time of an existing control node, in which case the parameters of that control node are changed.
Implements OpenSim::Control.
setControlValueMin()
void OpenSim::ControlLinear::setControlValueMin (double aT, double aX) override virtual
This method adds a set of control parameters at the specified time unless the specified time equals the time of an existing control node, in which case the parameters of that control node are changed.
Implements OpenSim::Control.
setKp()
void OpenSim::ControlLinear::setKp (double aKp)
Sets the position gain for PD follower filter.
This value is relevant only if the PD follower filter will be used.
See also
setFilterOn()
Parameters
aKp Value of position gain for the PD follower filter.
setKv()
void OpenSim::ControlLinear::setKv (double aKv)
Sets the velocity gain for PD follower filter.
This value is relevant only if the PD follower filter will be used.
See also
setFilterOn()
Parameters
aKv Value of velocity gain for the PD follower filter.
setParameterMax()
void OpenSim::ControlLinear::setParameterMax (int aI, double aMax) override virtual
Set the maximum value that a control parameter can take on.
Parameters
aI Index of the parameter.
aMax Maximum value the parameter can have.
Exceptions
Exception if aI is invalid.
Implements OpenSim::Control.
setParameterMin()
void OpenSim::ControlLinear::setParameterMin (int aI, double aMin) override virtual
Sets the minimum value that a control parameter can take on.
Parameters
aI Index of the parameter.
aMin Minimum value the parameter can have.
Exceptions
Exception if aI is invalid.
Implements OpenSim::Control.
setParameterValue()
void OpenSim::ControlLinear::setParameterValue (int aI, double aP) override virtual
Parameters
aI Index of the parameter.
aP The parameter value is simply the value of the aI-th ControlLinearNode (which is the value of the control curve).
Implements OpenSim::Control.
setupProperties()
void OpenSim::ControlLinear::setupProperties () override protected virtual
Connect properties to local pointers.
Reimplemented from OpenSim::Control.
setUseSteps()
void OpenSim::ControlLinear::setUseSteps (bool aTrueFalse)
Sets whether or not step functions are used between control nodes or linear interpolation.
When step functions are used, the value of the control curve between two nodes is the value of the node that occurs later in time.
Parameters
aTrueFalse If true, step functions will be used to determine the value between adjacent nodes. If false, linear interpolation will be used.
simplify() [1/2]
void OpenSim::ControlLinear::simplify (const PropertySet & aProperties) override virtual
The number of control nodes is reduced by first applying a lowpass filter to the sequence of control nodes using a specified cutoff frequency and then removing nodes that keep the curve within a specified distance to the low-pass filtered curve.
The PropertySet should contain:
TYPE NAME
PropertyDbl cutoff_frequency
PropertyDbl distance
Parameters
aProperties PropertySet containing the needed properties for this method.
Exceptions
Exception if an error is encountered.
Reimplemented from OpenSim::Control.
simplify() [2/2]
bool OpenSim::ControlLinear::simplify (const double & cutoffFrequency, const double & distance)
Another interface to simplify that: (1) does not require properties, and (2) returns bool on failure for a more graceful batch simplification.
The documentation for this class was generated from the following file:
OpenSim/Simulation/Control/ControlLinear.h