API: OpenSim::MocoDirectCollocationSolver Class Reference
OpenSim::MocoDirectCollocationSolver Class Reference abstract
This is a base class for solvers that use direct collocation to convert an optimal control problem into a generic nonlinear programming problem.
OpenSim Properties, Sockets, Outputs, Inputs
Properties (single-value)
int num_mesh_intervals
"The number of uniformly-sized mesh intervals for the problem " "(default: 100). If a non-uniform mesh exists, the non-uniform " "mesh is used instead."
int verbosity
"0 for silent. 1 for only Moco's own output. " "2 for output from CasADi and the underlying solver (default: 2)."
std::string transcription_scheme
"'trapezoidal' for trapezoidal transcription, or 'hermite-simpson' " "(default) for separated Hermite-Simpson transcription."
bool interpolate_control_midpoints
"If the transcription scheme is set to 'hermite-simpson', then " "enable this property to constrain the control values at mesh " "interval midpoints to be linearly interpolated from the control " "values at the mesh interval endpoints. Default: true."
std::string multibody_dynamics_mode
"Multibody dynamics are expressed as 'explicit' (default) or " "'implicit' differential equations."
std::string optim_solver
"The optimization solver to use (default: ipopt)."
int optim_max_iterations
"Maximum number of iterations in the optimization solver " "(-1 for solver's default)."
double optim_convergence_tolerance
"Tolerance used to determine if the objective is minimized " "(-1 for solver's default)"
double optim_constraint_tolerance
"Tolerance used to determine if the constraints are satisfied " "(-1 for solver's default)"
std::string optim_hessian_approximation
"When using IPOPT, 'limited-memory' (default) for quasi-Newton, or " "'exact' for full " "Newton."
int optim_ipopt_print_level
"IPOPT's verbosity (see IPOPT documentation)."
bool minimize_lagrange_multipliers
"If enabled, a term minimizing the weighted, squared sum of " "any existing Lagrange multipliers is added to the optimal control " "problem. This may be useful for imposing uniqueness in the " "Lagrange multipliers when not enforcing model kinematic " "constraint derivatives or when the constraint Jacobian is " "singular. To set the weight for this term use the " "'lagrange_multiplier_weight' property. Default: false"
double lagrange_multiplier_weight
"If the 'minimize_lagrange_multipliers' property is enabled, this " "defines the weight for the cost term added to the optimal control " "problem. Default: 1"
MocoBounds velocity_correction_bounds
"For problems where model kinematic constraint derivatives are " "enforced, set the bounds on the slack variables performing the " "velocity correction to project the model coordinates back onto " "the constraint manifold. Default: [-0.1, 0.1]"
MocoBounds implicit_multibody_acceleration_bounds
"Bounds on acceleration variables in implicit dynamics mode. " "Default: [-1000, 1000]"
MocoBounds implicit_auxiliary_derivative_bounds
"Bounds on derivative variables for components with auxiliary " "dynamics in implicit form. Default: [-1000, 1000]"
std::string guess_file
"A MocoTrajectory file storing an initial guess."
Properties (optional)
bool enforce_constraint_derivatives
"'true' (default) or 'false', whether or not derivatives of " "kinematic constraints are enforced as path constraints in the " "optimal control problem."
Properties (list)
double mesh
"Usually non-uniform, user-defined list of mesh points to sample. " "Takes precedence over uniform mesh with num_mesh_intervals."
Public Member Functions
MocoDirectCollocationSolver ()
void setMesh (const std::vector< double > &mesh)
Set the mesh to a user-defined list of mesh points to sample.
Public Member Functions inherited from OpenSim::MocoSolver
MocoSolver ()=default
MocoSolver (const MocoProblem &problem)
This calls resetProblem() with the provided problem.
virtual ~MocoSolver ()=default
void resetProblem (const MocoProblem &problem) const
Call this to prepare the solver for use on the provided problem.
MocoTrajectory createGuessTimeStepping () const
(Experimental) Run a forward simulation (using the OpenSim Manager, which uses a SimTK::Integrator), using the default controls for actuators and the default states as the initial states, to create a guess that is dynamically consistent (constraint errors should be small).
Public Member Functions inherited from OpenSim::Object
virtual ~Object ()
Virtual destructor for cleanup.
bool isEqualTo (const Object &aObject) const
Equality operator wrapper for use from languages not supporting operator overloading.
Object & operator= (const Object &aObject)
Copy assignment copies he base class fields, including the properties.
virtual bool operator== (const Object &aObject) const
Determine if two objects are equal.
virtual bool operator< (const Object &aObject) const
Provide an ordering for objects so they can be put in sorted containers.
void setName (const std::string &name)
Set the name of the Object.
const std::string & getName () const
Get the name of this Object.
void setDescription (const std::string &description)
Set description, a one-liner summary.
const std::string & getDescription () const
Get description, a one-liner summary.
const std::string & getAuthors () const
Get Authors of this Object.
void setAuthors (const std::string &authors)
Set Authors of this object.
const std::string & getReferences () const
Get references or publications to cite if using this object.
void setReferences (const std::string &references)
Set references or publications to cite if using this object.
int getNumProperties () const
Determine how many properties are stored with this Object.
const AbstractProperty & getPropertyByIndex (int propertyIndex) const
Get a const reference to a property by its index number, returned as an AbstractProperty.
AbstractProperty & updPropertyByIndex (int propertyIndex)
Get a writable reference to a property by its index number, returned as an AbstractProperty.
bool hasProperty (const std::string &name) const
Return true if this Object has a property of any type with the given name, which must not be empty.
const AbstractProperty & getPropertyByName (const std::string &name) const
Get a const reference to a property by its name, returned as an AbstractProperty.
AbstractProperty & updPropertyByName (const std::string &name)
Get a writable reference to a property by its name, returned as an AbstractProperty.
template<class T >
bool hasProperty () const
Return true if this Object contains an unnamed, one-object property that contains objects of the given template type T.
template<class T >
const Property< T > & getProperty (const PropertyIndex &index) const
Get property of known type Property<T> as a const reference; the property must be present and have the right type.
template<class T >
Property< T > & updProperty (const PropertyIndex &index)
Get property of known type Property<T> as a writable reference; the property must be present and have the right type.
bool isObjectUpToDateWithProperties () const
Returns true if no property's value has changed since the last time setObjectIsUpToDateWithProperties() was called.
void readObjectFromXMLNodeOrFile (SimTK::Xml::Element &objectElement, int versionNumber)
We're given an XML element from which we are to populate this Object.
virtual void updateFromXMLNode (SimTK::Xml::Element &objectElement, int versionNumber)
Use this method to deserialize an object from a SimTK::Xml::Element.
void updateXMLNode (SimTK::Xml::Element &parent, const AbstractProperty *prop=nullptr) const
Serialize this object into the XML node that represents it.
bool getInlined () const
Inlined means an in-memory Object that is not associated with an XMLDocument.
void setInlined (bool aInlined, const std::string &aFileName="")
Mark this as inlined or not and optionally provide a file name to associate with the new XMLDocument for the non-inline case.
std::string getDocumentFileName () const
If there is a document associated with this object then return the file name maintained by the document.
int getDocumentFileVersion () const
If there is a document associated with this object then return its version number.
void setAllPropertiesUseDefault (bool aUseDefault)
bool print (const std::string &fileName) const
Write this Object into an XML file of the given name; conventionally the suffix to use is ".osim".
std::string dump () const
dump the XML representation of this Object into an std::string and return it.
virtual bool isA (const char *type) const
The default implementation returns true only if the supplied string is "Object"; each Object-derived class overrides this to match its own class name.
const std::string & toString () const
Wrapper to be used on Java side to display objects in tree; this returns just the object's name.
PropertySet & getPropertySet ()
OBSOLETE: Get a reference to the PropertySet maintained by the Object.
const PropertySet & getPropertySet () const
Auto-generated functions
static MocoDirectCollocationSolver * safeDownCast (OpenSim::Object *obj)
For use in MATLAB and Python to access the concrete class.
static const std::string & getClassName ()
This returns "MocoDirectCollocationSolver".
MocoDirectCollocationSolver * clone () const override=0
Create a new heap-allocated copy of the concrete object to which this Object refers.
const std::string & getConcreteClassName () const override=0
Returns the class name of the concrete Object-derived class of the actual object referenced by this Object, as a string.
Property-related functions
const int & get_num_mesh_intervals () const
Get the value of the num_mesh_intervals property.
int & upd_num_mesh_intervals ()
Get a writable reference to the num_mesh_intervals property.
void set_num_mesh_intervals (const int &value)
Set the value of the num_mesh_intervals property.
const int & get_verbosity () const
Get the value of the verbosity property.
int & upd_verbosity ()
Get a writable reference to the verbosity property.
void set_verbosity (const int &value)
Set the value of the verbosity property.
const std::string & get_transcription_scheme () const
Get the value of the transcription_scheme property.
std::string & upd_transcription_scheme ()
Get a writable reference to the transcription_scheme property.
void set_transcription_scheme (const std::string &value)
Set the value of the transcription_scheme property.
const bool & get_interpolate_control_midpoints () const
Get the value of the interpolate_control_midpoints property.
bool & upd_interpolate_control_midpoints ()
Get a writable reference to the interpolate_control_midpoints property.
void set_interpolate_control_midpoints (const bool &value)
Set the value of the interpolate_control_midpoints property.
const std::string & get_multibody_dynamics_mode () const
Get the value of the multibody_dynamics_mode property.
std::string & upd_multibody_dynamics_mode ()
Get a writable reference to the multibody_dynamics_mode property.
void set_multibody_dynamics_mode (const std::string &value)
Set the value of the multibody_dynamics_mode property.
const std::string & get_optim_solver () const
Get the value of the optim_solver property.
std::string & upd_optim_solver ()
Get a writable reference to the optim_solver property.
void set_optim_solver (const std::string &value)
Set the value of the optim_solver property.
const int & get_optim_max_iterations () const
Get the value of the optim_max_iterations property.
int & upd_optim_max_iterations ()
Get a writable reference to the optim_max_iterations property.
void set_optim_max_iterations (const int &value)
Set the value of the optim_max_iterations property.
const double & get_optim_convergence_tolerance () const
Get the value of the optim_convergence_tolerance property.
double & upd_optim_convergence_tolerance ()
Get a writable reference to the optim_convergence_tolerance property.
void set_optim_convergence_tolerance (const double &value)
Set the value of the optim_convergence_tolerance property.
const double & get_optim_constraint_tolerance () const
Get the value of the optim_constraint_tolerance property.
double & upd_optim_constraint_tolerance ()
Get a writable reference to the optim_constraint_tolerance property.
void set_optim_constraint_tolerance (const double &value)
Set the value of the optim_constraint_tolerance property.
const std::string & get_optim_hessian_approximation () const
Get the value of the optim_hessian_approximation property.
std::string & upd_optim_hessian_approximation ()
Get a writable reference to the optim_hessian_approximation property.
void set_optim_hessian_approximation (const std::string &value)
Set the value of the optim_hessian_approximation property.
const int & get_optim_ipopt_print_level () const
Get the value of the optim_ipopt_print_level property.
int & upd_optim_ipopt_print_level ()
Get a writable reference to the optim_ipopt_print_level property.
void set_optim_ipopt_print_level (const int &value)
Set the value of the optim_ipopt_print_level property.
const bool & get_enforce_constraint_derivatives () const
Get the value of the enforce_constraint_derivatives property.
bool & upd_enforce_constraint_derivatives ()
Get a writable reference to the enforce_constraint_derivatives property.
void set_enforce_constraint_derivatives (const bool &value)
Set the value of the enforce_constraint_derivatives property.
const bool & get_minimize_lagrange_multipliers () const
Get the value of the minimize_lagrange_multipliers property.
bool & upd_minimize_lagrange_multipliers ()
Get a writable reference to the minimize_lagrange_multipliers property.
void set_minimize_lagrange_multipliers (const bool &value)
Set the value of the minimize_lagrange_multipliers property.
const double & get_lagrange_multiplier_weight () const
Get the value of the lagrange_multiplier_weight property.
double & upd_lagrange_multiplier_weight ()
Get a writable reference to the lagrange_multiplier_weight property.
void set_lagrange_multiplier_weight (const double &value)
Set the value of the lagrange_multiplier_weight property.
const MocoBounds & get_velocity_correction_bounds () const
Get the value of the velocity_correction_bounds property.
MocoBounds & upd_velocity_correction_bounds ()
Get a writable reference to the velocity_correction_bounds property.
void set_velocity_correction_bounds (const MocoBounds &value)
Set the value of the velocity_correction_bounds property.
const MocoBounds & get_implicit_multibody_acceleration_bounds () const
Get the value of the implicit_multibody_acceleration_bounds property.
MocoBounds & upd_implicit_multibody_acceleration_bounds ()
Get a writable reference to the implicit_multibody_acceleration_bounds property.
void set_implicit_multibody_acceleration_bounds (const MocoBounds &value)
Set the value of the implicit_multibody_acceleration_bounds property.
const MocoBounds & get_implicit_auxiliary_derivative_bounds () const
Get the value of the implicit_auxiliary_derivative_bounds property.
MocoBounds & upd_implicit_auxiliary_derivative_bounds ()
Get a writable reference to the implicit_auxiliary_derivative_bounds property.
void set_implicit_auxiliary_derivative_bounds (const MocoBounds &value)
Set the value of the implicit_auxiliary_derivative_bounds property.
const std::string & get_guess_file () const
Get the value of the guess_file property.
std::string & upd_guess_file ()
Get a writable reference to the guess_file property.
void set_guess_file (const std::string &value)
Set the value of the guess_file property.
const double & get_mesh (int i) const
Get the value of the i-th element of the mesh property.
double & upd_mesh (int i)
Get a writable reference to the i-th element of the mesh property.
void set_mesh (int i, const double &value)
Set the value of the i-th element of mesh property.
int append_mesh (const double &value)
Append an element to the mesh property.
Additional Inherited Members
Static Public Member Functions inherited from OpenSim::MocoSolver
static MocoSolver * safeDownCast (OpenSim::Object *obj)
For use in MATLAB and Python to access the concrete class.
static const std::string & getClassName ()
This returns "MocoSolver".
Static Public Member Functions inherited from OpenSim::Object
static void registerType (const Object &defaultObject)
Register an instance of a class; if the class is already registered it will be replaced.
static void renameType (const std::string &oldTypeName, const std::string &newTypeName)
Support versioning by associating the current Object type with an old name.
static const Object * getDefaultInstanceOfType (const std::string &concreteClassName)
Return a pointer to the default instance of the registered (concrete) Object whose class name is given, or NULL if the type is not registered.
template<class T >
static bool isObjectTypeDerivedFrom (const std::string &concreteClassName)
Return true if the given concrete object type represents a subclass of the template object type T, and thus could be referenced with a T*.
static Object * newInstanceOfType (const std::string &concreteClassName)
Create a new instance of the concrete Object type whose class name is given as concreteClassName.
static void getRegisteredTypenames (Array< std::string > &typeNames)
Retrieve all the typenames registered so far.
template<class T >
static void getRegisteredObjectsOfGivenType (ArrayPtrs< T > &rArray)
Return an array of pointers to the default instances of all registered (concrete) Object types that derive from a given Object-derived type that does not have to be concrete.
static bool PrintPropertyInfo (std::ostream &os, const std::string &classNameDotPropertyName, bool printFlagInfo=true)
Dump formatted property information to a given output stream, useful for creating a "help" facility for registered objects.
static bool PrintPropertyInfo (std::ostream &os, const std::string &className, const std::string &propertyName, bool printFlagInfo=true)
Same as the other signature but the class name and property name are provided as two separate strings.
static Object * makeObjectFromFile (const std::string &fileName)
Create an OpenSim object whose type is based on the tag at the root node of the XML file passed in.
static const std::string & getClassName ()
Return the name of this class as a string; i.e., "Object".
static void setSerializeAllDefaults (bool shouldSerializeDefaults)
Static function to control whether all registered objects and their properties are written to the defaults section of output files rather than only those values for which the default was explicitly overwritten when read in from an input file or set programmatically.
static bool getSerializeAllDefaults ()
Report the value of the "serialize all defaults" flag.
static bool isKindOf (const char *type)
Returns true if the passed-in string is "Object"; each Object-derived class defines a method of this name for its own class name.
static void setDebugLevel (int newLevel)
Set the amount of logging output.
static int getDebugLevel ()
Get the current setting of debug level.
static Object * SafeCopy (const Object *aObject)
Use the clone() method to duplicate the given object unless the pointer is null in which case null is returned.
static void RegisterType (const Object &defaultObject)
OBSOLETE alternate name for registerType().
static void RenameType (const std::string &oldName, const std::string &newName)
OBSOLETE alternate name for renameType().
Detailed Description
This is a base class for solvers that use direct collocation to convert an optimal control problem into a generic nonlinear programming problem.
The best resource for learning about direct collocation is the Betts textbook:
Betts, John T. Practical methods for optimal control and estimation using nonlinear programming. Vol. 19. Siam, 2010.
MocoDirectCollocationSolver
Transcription scheme
The transcription_scheme setting allows you to choose between 'trapezoidal' and 'hermite-simpson' transcription schemes. The 'trapezoidal' option replaces the dynamics differential constraints with finite differences based on trapezoidal rule integration. The 'hermite-simpson' option uses a Hermite interpolant and Simpson integration to construct the finite differences. The 'hermite-simpson' option uses the separated Hermite-Simpson transcription approach, which allows control values at mesh interval midpoints to be free variables (see Betts textbook for more details). The setting interpolate_control_midpoints constrains control midpoint variables to be linearly interpolated from the mesh interval endpoint values (default and recommended setting). If solving problems including model kinematic constraints, the 'hermite-simpson' option is required (see Kinematic constraints section below).
Path constraints on controls with Hermite-Simpson transcription
For Hermite-Simpson transcription, the direct collocation solvers enforce the path constraints (e.g., MocoPathConstraint) at only the mesh interval endpoints (not midpoints), but control signal variables exist at both mesh interval endpoints and midpoints. Keep this in mind when using path constraints on controls (e.g., MocoControlBoundConstraint). If interpolate_control_midpoints is false, the values of a control at midpoints may differ greatly from the values at mesh interval endpoints.
Multibody dynamics mode
The multibody_dynamics_mode setting allows you to choose between expressing multibody dynamics as explicit differential equations (e.g., \(\dot{y} = f(y) \)) or implicit differential equations (e.g., \(0 = f(y, \dot{y}) \), or inverse dynamics). Whether auxiliary dynamics (e.g., muscle fiber and activation dynamics) are implicit or explicit depends on the model component implementing those dynamics.
Kinematic constraints
All holonomic kinematic constraints included as OpenSim model constraints are supported. Both the 'trapezoidal' and 'hermite-simpson' transcription schemes support kinematic constraints, but the 'hermite-transcription' scheme handles kinematic constraints much more robustly; in practice, the 'trapezoidal' scheme is not used for models with kinematic constraints. Kinematic constraints are automatically detected if present in the model and are converted to path constraints in the optimal control problem based on the method presented in Posa et al. 2016, 'Optimization and stabilization of trajectories for constrained dynamical systems'; see Kinematic constraints. The minimize_lagrange_multipliers and lagrange_multiplier_weight settings allow you to enable and set the weight for the minimization of all Lagrange multipliers associated with kinematic constraints in the problem. The velocity_correction_bounds setting allows you to set the bounds on the velocity correction variables that project state variables onto the constraint manifold when necessary to properly enforce defect constraints (see Posa et al. 2016 for details).
Constructor & Destructor Documentation
MocoDirectCollocationSolver()
OpenSim::MocoDirectCollocationSolver::MocoDirectCollocationSolver () inline
Member Function Documentation
append_mesh()
int OpenSim::MocoDirectCollocationSolver::append_mesh (const double & value) inline protected
Append an element to the mesh property.
clone()
MocoDirectCollocationSolver* OpenSim::MocoDirectCollocationSolver::clone () const override pure virtual
Create a new heap-allocated copy of the concrete object to which this Object refers.
It is up to the caller to delete the returned object when no longer needed. Every concrete object deriving from Object implements this pure virtual method automatically, via the declaration macro it invokes (e.g., OpenSim_DECLARE_CONCRETE_OBJECT()). Note that the concrete class overrides modify the return type to be a pointer to the concrete object; that still overrides the base class method because the return type is covariant with (that is, derives from) Object.
Implements OpenSim::MocoSolver.
Implemented in OpenSim::MocoCasADiSolver, and OpenSim::MocoTropterSolver.
constructProperties()
void OpenSim::MocoDirectCollocationSolver::constructProperties () protected
get_enforce_constraint_derivatives()
const bool& OpenSim::MocoDirectCollocationSolver::get_enforce_constraint_derivatives () const inline
Get the value of the enforce_constraint_derivatives property.
Referenced by OpenSim::MocoTropterSolver::TropterProblemBase< T >::addKinematicConstraints(), and OpenSim::MocoTropterSolver::TropterProblemBase< T >::calcKinematicConstraintErrors().
get_guess_file()
const std::string& OpenSim::MocoDirectCollocationSolver::get_guess_file () const inline protected
Get the value of the guess_file property.
get_implicit_auxiliary_derivative_bounds()
const MocoBounds& OpenSim::MocoDirectCollocationSolver::get_implicit_auxiliary_derivative_bounds () const inline
Get the value of the implicit_auxiliary_derivative_bounds property.
get_implicit_multibody_acceleration_bounds()
const MocoBounds& OpenSim::MocoDirectCollocationSolver::get_implicit_multibody_acceleration_bounds () const inline
Get the value of the implicit_multibody_acceleration_bounds property.
Referenced by OpenSim::MocoTropterSolver::ImplicitTropterProblem< T >::ImplicitTropterProblem().
get_interpolate_control_midpoints()
const bool& OpenSim::MocoDirectCollocationSolver::get_interpolate_control_midpoints () const inline
Get the value of the interpolate_control_midpoints property.
get_lagrange_multiplier_weight()
const double& OpenSim::MocoDirectCollocationSolver::get_lagrange_multiplier_weight () const inline
Get the value of the lagrange_multiplier_weight property.
Referenced by OpenSim::MocoTropterSolver::TropterProblemBase< T >::calc_cost_integrand().
get_mesh()
const double& OpenSim::MocoDirectCollocationSolver::get_mesh (int i) const inline protected
Get the value of the i-th element of the mesh property.
get_minimize_lagrange_multipliers()
const bool& OpenSim::MocoDirectCollocationSolver::get_minimize_lagrange_multipliers () const inline
Get the value of the minimize_lagrange_multipliers property.
Referenced by OpenSim::MocoTropterSolver::TropterProblemBase< T >::addCosts(), and OpenSim::MocoTropterSolver::TropterProblemBase< T >::addKinematicConstraints().
get_multibody_dynamics_mode()
const std::string& OpenSim::MocoDirectCollocationSolver::get_multibody_dynamics_mode () const inline
Get the value of the multibody_dynamics_mode property.
get_num_mesh_intervals()
const int& OpenSim::MocoDirectCollocationSolver::get_num_mesh_intervals () const inline
Get the value of the num_mesh_intervals property.
get_optim_constraint_tolerance()
const double& OpenSim::MocoDirectCollocationSolver::get_optim_constraint_tolerance () const inline
Get the value of the optim_constraint_tolerance property.
get_optim_convergence_tolerance()
const double& OpenSim::MocoDirectCollocationSolver::get_optim_convergence_tolerance () const inline
Get the value of the optim_convergence_tolerance property.
get_optim_hessian_approximation()
const std::string& OpenSim::MocoDirectCollocationSolver::get_optim_hessian_approximation () const inline
Get the value of the optim_hessian_approximation property.
get_optim_ipopt_print_level()
const int& OpenSim::MocoDirectCollocationSolver::get_optim_ipopt_print_level () const inline
Get the value of the optim_ipopt_print_level property.
get_optim_max_iterations()
const int& OpenSim::MocoDirectCollocationSolver::get_optim_max_iterations () const inline
Get the value of the optim_max_iterations property.
get_optim_solver()
const std::string& OpenSim::MocoDirectCollocationSolver::get_optim_solver () const inline
Get the value of the optim_solver property.
get_transcription_scheme()
const std::string& OpenSim::MocoDirectCollocationSolver::get_transcription_scheme () const inline
Get the value of the transcription_scheme property.
get_velocity_correction_bounds()
const MocoBounds& OpenSim::MocoDirectCollocationSolver::get_velocity_correction_bounds () const inline
Get the value of the velocity_correction_bounds property.
Referenced by OpenSim::MocoTropterSolver::TropterProblemBase< T >::addKinematicConstraints().
get_verbosity()
const int& OpenSim::MocoDirectCollocationSolver::get_verbosity () const inline
Get the value of the verbosity property.
getClassName()
static const std::string& OpenSim::MocoDirectCollocationSolver::getClassName () inline static
This returns "MocoDirectCollocationSolver".
See getConcreteClassName() if you want the class name of the underlying concrete object instead.
getConcreteClassName()
const std::string& OpenSim::MocoDirectCollocationSolver::getConcreteClassName () const override pure virtual
Returns the class name of the concrete Object-derived class of the actual object referenced by this Object, as a string.
This is the string that is used as the tag for this concrete object in an XML file. Every concrete class derived from Object automatically overrides this method via the declaration macro it uses. See getClassName() to get the class name of the referencing (possibly abstract) class rather than the concrete object.
See also
getClassName()
Implements OpenSim::MocoSolver.
Implemented in OpenSim::MocoCasADiSolver, and OpenSim::MocoTropterSolver.
safeDownCast()
static MocoDirectCollocationSolver* OpenSim::MocoDirectCollocationSolver::safeDownCast (OpenSim::Object * obj) inline static
For use in MATLAB and Python to access the concrete class.
Example: cObj = MocoDirectCollocationSolver.safeDownCast(obj). This is equivalent to dynamic_cast<MocoDirectCollocationSolver*>(obj) in C++.
set_enforce_constraint_derivatives()
void OpenSim::MocoDirectCollocationSolver::set_enforce_constraint_derivatives (const bool & value) inline
Set the value of the enforce_constraint_derivatives property.
set_guess_file()
void OpenSim::MocoDirectCollocationSolver::set_guess_file (const std::string & value) inline protected
Set the value of the guess_file property.
set_implicit_auxiliary_derivative_bounds()
void OpenSim::MocoDirectCollocationSolver::set_implicit_auxiliary_derivative_bounds (const MocoBounds & value) inline
Set the value of the implicit_auxiliary_derivative_bounds property.
set_implicit_multibody_acceleration_bounds()
void OpenSim::MocoDirectCollocationSolver::set_implicit_multibody_acceleration_bounds (const MocoBounds & value) inline
Set the value of the implicit_multibody_acceleration_bounds property.
set_interpolate_control_midpoints()
void OpenSim::MocoDirectCollocationSolver::set_interpolate_control_midpoints (const bool & value) inline
Set the value of the interpolate_control_midpoints property.
set_lagrange_multiplier_weight()
void OpenSim::MocoDirectCollocationSolver::set_lagrange_multiplier_weight (const double & value) inline
Set the value of the lagrange_multiplier_weight property.
set_mesh()
void OpenSim::MocoDirectCollocationSolver::set_mesh (int i, const double & value) inline protected
Set the value of the i-th element of mesh property.
set_minimize_lagrange_multipliers()
void OpenSim::MocoDirectCollocationSolver::set_minimize_lagrange_multipliers (const bool & value) inline
Set the value of the minimize_lagrange_multipliers property.
set_multibody_dynamics_mode()
void OpenSim::MocoDirectCollocationSolver::set_multibody_dynamics_mode (const std::string & value) inline
Set the value of the multibody_dynamics_mode property.
set_num_mesh_intervals()
void OpenSim::MocoDirectCollocationSolver::set_num_mesh_intervals (const int & value) inline
Set the value of the num_mesh_intervals property.
Examples:
example2DWalking.cpp, example2DWalkingMetabolics.cpp, exampleMarkerTracking.cpp, exampleMocoCustomEffortGoal.cpp, exampleSlidingMass.cpp, exampleSlidingMassAdvanced.cpp, and exampleTracking.cpp.
set_optim_constraint_tolerance()
void OpenSim::MocoDirectCollocationSolver::set_optim_constraint_tolerance (const double & value) inline
Set the value of the optim_constraint_tolerance property.
Examples:
example2DWalking.cpp, and example2DWalkingMetabolics.cpp.
set_optim_convergence_tolerance()
void OpenSim::MocoDirectCollocationSolver::set_optim_convergence_tolerance (const double & value) inline
Set the value of the optim_convergence_tolerance property.
Examples:
example2DWalking.cpp, and example2DWalkingMetabolics.cpp.
set_optim_hessian_approximation()
void OpenSim::MocoDirectCollocationSolver::set_optim_hessian_approximation (const std::string & value) inline
Set the value of the optim_hessian_approximation property.
set_optim_ipopt_print_level()
void OpenSim::MocoDirectCollocationSolver::set_optim_ipopt_print_level (const int & value) inline
Set the value of the optim_ipopt_print_level property.
set_optim_max_iterations()
void OpenSim::MocoDirectCollocationSolver::set_optim_max_iterations (const int & value) inline
Set the value of the optim_max_iterations property.
Examples:
example2DWalking.cpp, and example2DWalkingMetabolics.cpp.
set_optim_solver()
void OpenSim::MocoDirectCollocationSolver::set_optim_solver (const std::string & value) inline
Set the value of the optim_solver property.
Examples:
example2DWalking.cpp, and example2DWalkingMetabolics.cpp.
set_transcription_scheme()
void OpenSim::MocoDirectCollocationSolver::set_transcription_scheme (const std::string & value) inline
Set the value of the transcription_scheme property.
set_velocity_correction_bounds()
void OpenSim::MocoDirectCollocationSolver::set_velocity_correction_bounds (const MocoBounds & value) inline
Set the value of the velocity_correction_bounds property.
set_verbosity()
void OpenSim::MocoDirectCollocationSolver::set_verbosity (const int & value) inline
Set the value of the verbosity property.
Examples:
example2DWalking.cpp, and example2DWalkingMetabolics.cpp.
setMesh()
void OpenSim::MocoDirectCollocationSolver::setMesh (const std::vector< double > & mesh)
Set the mesh to a user-defined list of mesh points to sample.
This takes precedence over the uniform mesh that would be specified with num_mesh_intervals. The user-defined mesh must start with 0, be strictly increasing (no duplicate entries), and end with 1.
upd_enforce_constraint_derivatives()
bool& OpenSim::MocoDirectCollocationSolver::upd_enforce_constraint_derivatives () inline
Get a writable reference to the enforce_constraint_derivatives property.
upd_guess_file()
std::string& OpenSim::MocoDirectCollocationSolver::upd_guess_file () inline protected
Get a writable reference to the guess_file property.
upd_implicit_auxiliary_derivative_bounds()
MocoBounds& OpenSim::MocoDirectCollocationSolver::upd_implicit_auxiliary_derivative_bounds () inline
Get a writable reference to the implicit_auxiliary_derivative_bounds property.
upd_implicit_multibody_acceleration_bounds()
MocoBounds& OpenSim::MocoDirectCollocationSolver::upd_implicit_multibody_acceleration_bounds () inline
Get a writable reference to the implicit_multibody_acceleration_bounds property.
upd_interpolate_control_midpoints()
bool& OpenSim::MocoDirectCollocationSolver::upd_interpolate_control_midpoints () inline
Get a writable reference to the interpolate_control_midpoints property.
upd_lagrange_multiplier_weight()
double& OpenSim::MocoDirectCollocationSolver::upd_lagrange_multiplier_weight () inline
Get a writable reference to the lagrange_multiplier_weight property.
upd_mesh()
double& OpenSim::MocoDirectCollocationSolver::upd_mesh (int i) inline protected
Get a writable reference to the i-th element of the mesh property.
upd_minimize_lagrange_multipliers()
bool& OpenSim::MocoDirectCollocationSolver::upd_minimize_lagrange_multipliers () inline
Get a writable reference to the minimize_lagrange_multipliers property.
upd_multibody_dynamics_mode()
std::string& OpenSim::MocoDirectCollocationSolver::upd_multibody_dynamics_mode () inline
Get a writable reference to the multibody_dynamics_mode property.
upd_num_mesh_intervals()
int& OpenSim::MocoDirectCollocationSolver::upd_num_mesh_intervals () inline
Get a writable reference to the num_mesh_intervals property.
upd_optim_constraint_tolerance()
double& OpenSim::MocoDirectCollocationSolver::upd_optim_constraint_tolerance () inline
Get a writable reference to the optim_constraint_tolerance property.
upd_optim_convergence_tolerance()
double& OpenSim::MocoDirectCollocationSolver::upd_optim_convergence_tolerance () inline
Get a writable reference to the optim_convergence_tolerance property.
upd_optim_hessian_approximation()
std::string& OpenSim::MocoDirectCollocationSolver::upd_optim_hessian_approximation () inline
Get a writable reference to the optim_hessian_approximation property.
upd_optim_ipopt_print_level()
int& OpenSim::MocoDirectCollocationSolver::upd_optim_ipopt_print_level () inline
Get a writable reference to the optim_ipopt_print_level property.
upd_optim_max_iterations()
int& OpenSim::MocoDirectCollocationSolver::upd_optim_max_iterations () inline
Get a writable reference to the optim_max_iterations property.
upd_optim_solver()
std::string& OpenSim::MocoDirectCollocationSolver::upd_optim_solver () inline
Get a writable reference to the optim_solver property.
upd_transcription_scheme()
std::string& OpenSim::MocoDirectCollocationSolver::upd_transcription_scheme () inline
Get a writable reference to the transcription_scheme property.
upd_velocity_correction_bounds()
MocoBounds& OpenSim::MocoDirectCollocationSolver::upd_velocity_correction_bounds () inline
Get a writable reference to the velocity_correction_bounds property.
upd_verbosity()
int& OpenSim::MocoDirectCollocationSolver::upd_verbosity () inline
Get a writable reference to the verbosity property.
OpenSim Property, Socket, Output, Input Documentation
enforce_constraint_derivatives
bool OpenSim::MocoDirectCollocationSolver::enforce_constraint_derivatives
"'true' (default) or 'false', whether or not derivatives of " "kinematic constraints are enforced as path constraints in the " "optimal control problem."
This property appears in XML files under the tag <enforce_constraint_derivatives>. This property was generated with the OpenSim_DECLARE_OPTIONAL_PROPERTY macro; see Property to learn about the property system.
See also
get_enforce_constraint_derivatives(), upd_enforce_constraint_derivatives(), set_enforce_constraint_derivatives()
guess_file
std::string OpenSim::MocoDirectCollocationSolver::guess_file
"A MocoTrajectory file storing an initial guess."
This property appears in XML files under the tag <guess_file>. This property was generated with the OpenSim_DECLARE_PROPERTY macro; see Property to learn about the property system.
See also
get_guess_file(), upd_guess_file(), set_guess_file()
implicit_auxiliary_derivative_bounds
MocoBounds OpenSim::MocoDirectCollocationSolver::implicit_auxiliary_derivative_bounds
"Bounds on derivative variables for components with auxiliary " "dynamics in implicit form. Default: [-1000, 1000]"
This property appears in XML files under the tag <implicit_auxiliary_derivative_bounds>. This property was generated with the OpenSim_DECLARE_PROPERTY macro; see Property to learn about the property system.
See also
get_implicit_auxiliary_derivative_bounds(), upd_implicit_auxiliary_derivative_bounds(), set_implicit_auxiliary_derivative_bounds()
implicit_multibody_acceleration_bounds
MocoBounds OpenSim::MocoDirectCollocationSolver::implicit_multibody_acceleration_bounds
"Bounds on acceleration variables in implicit dynamics mode. " "Default: [-1000, 1000]"
This property appears in XML files under the tag <implicit_multibody_acceleration_bounds>. This property was generated with the OpenSim_DECLARE_PROPERTY macro; see Property to learn about the property system.
See also
get_implicit_multibody_acceleration_bounds(), upd_implicit_multibody_acceleration_bounds(), set_implicit_multibody_acceleration_bounds()
interpolate_control_midpoints
bool OpenSim::MocoDirectCollocationSolver::interpolate_control_midpoints
"If the transcription scheme is set to 'hermite-simpson', then " "enable this property to constrain the control values at mesh " "interval midpoints to be linearly interpolated from the control " "values at the mesh interval endpoints. Default: true."
This property appears in XML files under the tag <interpolate_control_midpoints>. This property was generated with the OpenSim_DECLARE_PROPERTY macro; see Property to learn about the property system.
See also
get_interpolate_control_midpoints(), upd_interpolate_control_midpoints(), set_interpolate_control_midpoints()
lagrange_multiplier_weight
double OpenSim::MocoDirectCollocationSolver::lagrange_multiplier_weight
"If the 'minimize_lagrange_multipliers' property is enabled, this " "defines the weight for the cost term added to the optimal control " "problem. Default: 1"
This property appears in XML files under the tag <lagrange_multiplier_weight>. This property was generated with the OpenSim_DECLARE_PROPERTY macro; see Property to learn about the property system.
See also
get_lagrange_multiplier_weight(), upd_lagrange_multiplier_weight(), set_lagrange_multiplier_weight()
mesh
double OpenSim::MocoDirectCollocationSolver::mesh
"Usually non-uniform, user-defined list of mesh points to sample. " "Takes precedence over uniform mesh with num_mesh_intervals."
This property appears in XML files under the tag <mesh>. This property holds a list of objects, and was generated with the OpenSim_DECLARE_LIST_PROPERTY macro; see Property to learn about the property system.
See also
get_mesh(), upd_mesh(), set_mesh(), append_mesh()
minimize_lagrange_multipliers
bool OpenSim::MocoDirectCollocationSolver::minimize_lagrange_multipliers
"If enabled, a term minimizing the weighted, squared sum of " "any existing Lagrange multipliers is added to the optimal control " "problem. This may be useful for imposing uniqueness in the " "Lagrange multipliers when not enforcing model kinematic " "constraint derivatives or when the constraint Jacobian is " "singular. To set the weight for this term use the " "'lagrange_multiplier_weight' property. Default: false"
This property appears in XML files under the tag <minimize_lagrange_multipliers>. This property was generated with the OpenSim_DECLARE_PROPERTY macro; see Property to learn about the property system.
See also
get_minimize_lagrange_multipliers(), upd_minimize_lagrange_multipliers(), set_minimize_lagrange_multipliers()
multibody_dynamics_mode
std::string OpenSim::MocoDirectCollocationSolver::multibody_dynamics_mode
"Multibody dynamics are expressed as 'explicit' (default) or " "'implicit' differential equations."
This property appears in XML files under the tag <multibody_dynamics_mode>. This property was generated with the OpenSim_DECLARE_PROPERTY macro; see Property to learn about the property system.
See also
get_multibody_dynamics_mode(), upd_multibody_dynamics_mode(), set_multibody_dynamics_mode()
num_mesh_intervals
int OpenSim::MocoDirectCollocationSolver::num_mesh_intervals
"The number of uniformly-sized mesh intervals for the problem " "(default: 100). If a non-uniform mesh exists, the non-uniform " "mesh is used instead."
This property appears in XML files under the tag <num_mesh_intervals>. This property was generated with the OpenSim_DECLARE_PROPERTY macro; see Property to learn about the property system.
See also
get_num_mesh_intervals(), upd_num_mesh_intervals(), set_num_mesh_intervals()
optim_constraint_tolerance
double OpenSim::MocoDirectCollocationSolver::optim_constraint_tolerance
"Tolerance used to determine if the constraints are satisfied " "(-1 for solver's default)"
This property appears in XML files under the tag <optim_constraint_tolerance>. This property was generated with the OpenSim_DECLARE_PROPERTY macro; see Property to learn about the property system.
See also
get_optim_constraint_tolerance(), upd_optim_constraint_tolerance(), set_optim_constraint_tolerance()
optim_convergence_tolerance
double OpenSim::MocoDirectCollocationSolver::optim_convergence_tolerance
"Tolerance used to determine if the objective is minimized " "(-1 for solver's default)"
This property appears in XML files under the tag <optim_convergence_tolerance>. This property was generated with the OpenSim_DECLARE_PROPERTY macro; see Property to learn about the property system.
See also
get_optim_convergence_tolerance(), upd_optim_convergence_tolerance(), set_optim_convergence_tolerance()
optim_hessian_approximation
std::string OpenSim::MocoDirectCollocationSolver::optim_hessian_approximation
"When using IPOPT, 'limited-memory' (default) for quasi-Newton, or " "'exact' for full " "Newton."
This property appears in XML files under the tag <optim_hessian_approximation>. This property was generated with the OpenSim_DECLARE_PROPERTY macro; see Property to learn about the property system.
See also
get_optim_hessian_approximation(), upd_optim_hessian_approximation(), set_optim_hessian_approximation()
optim_ipopt_print_level
int OpenSim::MocoDirectCollocationSolver::optim_ipopt_print_level
"IPOPT's verbosity (see IPOPT documentation)."
This property appears in XML files under the tag <optim_ipopt_print_level>. This property was generated with the OpenSim_DECLARE_PROPERTY macro; see Property to learn about the property system.
See also
get_optim_ipopt_print_level(), upd_optim_ipopt_print_level(), set_optim_ipopt_print_level()
optim_max_iterations
int OpenSim::MocoDirectCollocationSolver::optim_max_iterations
"Maximum number of iterations in the optimization solver " "(-1 for solver's default)."
This property appears in XML files under the tag <optim_max_iterations>. This property was generated with the OpenSim_DECLARE_PROPERTY macro; see Property to learn about the property system.
See also
get_optim_max_iterations(), upd_optim_max_iterations(), set_optim_max_iterations()
optim_solver
std::string OpenSim::MocoDirectCollocationSolver::optim_solver
"The optimization solver to use (default: ipopt)."
This property appears in XML files under the tag <optim_solver>. This property was generated with the OpenSim_DECLARE_PROPERTY macro; see Property to learn about the property system.
See also
get_optim_solver(), upd_optim_solver(), set_optim_solver()
transcription_scheme
std::string OpenSim::MocoDirectCollocationSolver::transcription_scheme
"'trapezoidal' for trapezoidal transcription, or 'hermite-simpson' " "(default) for separated Hermite-Simpson transcription."
This property appears in XML files under the tag <transcription_scheme>. This property was generated with the OpenSim_DECLARE_PROPERTY macro; see Property to learn about the property system.
See also
get_transcription_scheme(), upd_transcription_scheme(), set_transcription_scheme()
velocity_correction_bounds
MocoBounds OpenSim::MocoDirectCollocationSolver::velocity_correction_bounds
"For problems where model kinematic constraint derivatives are " "enforced, set the bounds on the slack variables performing the " "velocity correction to project the model coordinates back onto " "the constraint manifold. Default: [-0.1, 0.1]"
This property appears in XML files under the tag <velocity_correction_bounds>. This property was generated with the OpenSim_DECLARE_PROPERTY macro; see Property to learn about the property system.
See also
get_velocity_correction_bounds(), upd_velocity_correction_bounds(), set_velocity_correction_bounds()
verbosity
int OpenSim::MocoDirectCollocationSolver::verbosity
"0 for silent. 1 for only Moco's own output. " "2 for output from CasADi and the underlying solver (default: 2)."
This property appears in XML files under the tag <verbosity>. This property was generated with the OpenSim_DECLARE_PROPERTY macro; see Property to learn about the property system.
See also
get_verbosity(), upd_verbosity(), set_verbosity()
The documentation for this class was generated from the following file:
OpenSim/Moco/MocoDirectCollocationSolver.h