API: OpenSim::MocoTropterSolver::TropterProblemBase< T > Class Template Reference
OpenSim::MocoTropterSolver::TropterProblemBase< T > Class Template Reference
Public Member Functions
template<typename MocoTrajectoryType , typename tropIterateType >
MocoTrajectoryType convertIterateTropterToMoco (const tropIterateType &tropSol) const
MocoTrajectory convertToMocoTrajectory (const tropter::Iterate &tropSol) const
MocoSolution convertToMocoSolution (const tropter::Solution &tropSol) const
tropter::Iterate convertToTropterIterate (const MocoTrajectory &mocoIter) const
Constructor & Destructor Documentation
TropterProblemBase()
template<typename T > OpenSim::MocoTropterSolver::TropterProblemBase< T >::TropterProblemBase (const MocoTropterSolver & solver, bool implicit = false) inline protected
References OpenSim::MocoTropterSolver::TropterProblemBase< T >::addControlVariables(), OpenSim::MocoTropterSolver::TropterProblemBase< T >::addCosts(), OpenSim::MocoTropterSolver::TropterProblemBase< T >::addGenericPathConstraints(), OpenSim::MocoTropterSolver::TropterProblemBase< T >::addKinematicConstraints(), OpenSim::MocoTropterSolver::TropterProblemBase< T >::addParameters(), OpenSim::MocoTropterSolver::TropterProblemBase< T >::addStateVariables(), OpenSim::MocoProblemRep::createStateVariableNamesInSystemOrder(), OpenSim::getFormattedDateTime(), OpenSim::Model::getMatterSubsystem(), OpenSim::MocoProblemRep::getName(), OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_fileDeletionThrower, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_mocoProbRep, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_modelBase, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_stateBase, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_svNamesInSysOrder, and OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_yIndexMap.
Member Function Documentation
addControlVariables()
template<typename T > void OpenSim::MocoTropterSolver::TropterProblemBase< T >::addControlVariables () inline protected
References OpenSim::convertBounds(), OpenSim::createControlNamesFromModel(), OpenSim::MocoProblemRep::getControlInfo(), OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_mocoProbRep, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_modelBase, and OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_modelControlIndices.
Referenced by OpenSim::MocoTropterSolver::TropterProblemBase< T >::TropterProblemBase().
addCosts()
template<typename T > void OpenSim::MocoTropterSolver::TropterProblemBase< T >::addCosts () inline protected
References OpenSim::MocoProblemRep::createCostNames(), OpenSim::MocoDirectCollocationSolver::get_minimize_lagrange_multipliers(), OpenSim::MocoProblemRep::getCost(), OpenSim::MocoProblemRep::getNumEndpointConstraints(), OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_mocoProbRep, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_mocoTropterSolver, and OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_multiplierCostIndex.
Referenced by OpenSim::MocoTropterSolver::TropterProblemBase< T >::TropterProblemBase().
addGenericPathConstraints()
template<typename T > void OpenSim::MocoTropterSolver::TropterProblemBase< T >::addGenericPathConstraints () inline protected
Add any generic path constraints included in the problem.
References OpenSim::convertBounds(), OpenSim::MocoProblemRep::createPathConstraintNames(), OpenSim::MocoPathConstraint::getConstraintInfo(), OpenSim::MocoConstraintInfo::getConstraintLabels(), OpenSim::MocoProblemRep::getNumPathConstraintEquations(), OpenSim::MocoProblemRep::getPathConstraint(), OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_mocoProbRep, and OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_numPathConstraintEquations.
Referenced by OpenSim::MocoTropterSolver::TropterProblemBase< T >::TropterProblemBase().
addKinematicConstraints()
template<typename T > void OpenSim::MocoTropterSolver::TropterProblemBase< T >::addKinematicConstraints () inline protected
References OpenSim::Acceleration, OpenSim::convertBounds(), OpenSim::MocoProblemRep::createKinematicConstraintNames(), OpenSim::MocoDirectCollocationSolver::get_enforce_constraint_derivatives(), OpenSim::MocoDirectCollocationSolver::get_minimize_lagrange_multipliers(), OpenSim::MocoDirectCollocationSolver::get_velocity_correction_bounds(), OpenSim::MocoProblemRep::getKinematicConstraint(), OpenSim::MocoProblemRep::getMultiplierInfos(), OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_mocoProbRep, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_mocoTropterSolver, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_numKinematicConstraintEquations, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_numMultipliers, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_total_ma, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_total_mp, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_total_mv, OpenSim::Position, and OpenSim::Velocity.
Referenced by OpenSim::MocoTropterSolver::TropterProblemBase< T >::TropterProblemBase().
addParameters()
template<typename T > void OpenSim::MocoTropterSolver::TropterProblemBase< T >::addParameters () inline protected
References OpenSim::convertBounds(), OpenSim::MocoProblemRep::createParameterNames(), OpenSim::MocoParameter::getBounds(), OpenSim::MocoProblemRep::getParameter(), and OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_mocoProbRep.
Referenced by OpenSim::MocoTropterSolver::TropterProblemBase< T >::TropterProblemBase().
addStateVariables()
template<typename T > void OpenSim::MocoTropterSolver::TropterProblemBase< T >::addStateVariables () inline protected
References OpenSim::convertBounds(), OpenSim::MocoProblemRep::getStateInfo(), OpenSim::MocoProblemRep::getTimeFinalBounds(), OpenSim::MocoProblemRep::getTimeInitialBounds(), OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_mocoProbRep, and OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_svNamesInSysOrder.
Referenced by OpenSim::MocoTropterSolver::TropterProblemBase< T >::TropterProblemBase().
applyParametersToModelProperties()
template<typename T > void OpenSim::MocoTropterSolver::TropterProblemBase< T >::applyParametersToModelProperties (const tropter::VectorX< T > & parameters) const inline protected
Apply parameters to properties in m_modelBase and m_modelDisabledConstraints.
References OpenSim::MocoProblemRep::applyParametersToModelProperties(), and OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_mocoProbRep.
Referenced by OpenSim::MocoTropterSolver::TropterProblemBase< T >::initialize_on_iterate().
calc_cost()
template<typename T > void OpenSim::MocoTropterSolver::TropterProblemBase< T >::calc_cost (int cost_index, const tropter::CostInput< T > & in, T & cost_value) const inline override protected
References OpenSim::MocoGoal::calcGoal(), OpenSim::MocoProblemRep::getCostByIndex(), OpenSim::MocoProblemRep::getDiscreteControllerDisabledConstraints(), OpenSim::DiscreteController::getDiscreteControls(), OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_mocoProbRep, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_multiplierCostIndex, OpenSim::MocoTropterSolver::TropterProblemBase< T >::setSimTKStateForCostFinal(), OpenSim::MocoTropterSolver::TropterProblemBase< T >::setSimTKStateForCostInitial(), and OpenSim::MocoProblemRep::updStateDisabledConstraints().
calc_cost_integrand()
template<typename T > void OpenSim::MocoTropterSolver::TropterProblemBase< T >::calc_cost_integrand (int cost_index, const tropter::Input< T > & in, T & integrand) const inline override protected
References OpenSim::MocoGoal::calcIntegrand(), OpenSim::MocoDirectCollocationSolver::get_lagrange_multiplier_weight(), OpenSim::MocoProblemRep::getCostByIndex(), OpenSim::MocoProblemRep::getDiscreteControllerDisabledConstraints(), OpenSim::DiscreteController::getDiscreteControls(), OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_mocoProbRep, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_mocoTropterSolver, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_multiplierCostIndex, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_numMultipliers, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_stateDisabledConstraints, and OpenSim::MocoTropterSolver::TropterProblemBase< T >::setSimTKState().
calcAndApplyKinematicConstraintForces()
template<typename T > void OpenSim::MocoTropterSolver::TropterProblemBase< T >::calcAndApplyKinematicConstraintForces (const tropter::VectorX< T > & adjuncts, const SimTK::State & stateBase, SimTK::State & stateDisabledConstraints) const inline protected
References OpenSim::MocoProblemRep::getConstraintForces(), OpenSim::Model::getMatterSubsystem(), OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_constraintBodyForces, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_constraintMobilityForces, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_mocoProbRep, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_modelBase, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_numMultipliers, OpenSim::Model::realizeVelocity(), and OpenSim::DiscreteForces::setAllForces().
Referenced by OpenSim::MocoTropterSolver::TropterProblemBase< T >::setSimTKState().
calcKinematicConstraintErrors()
template<typename T > void OpenSim::MocoTropterSolver::TropterProblemBase< T >::calcKinematicConstraintErrors (const SimTK::Vector & udot, tropter::Output< T > & out) const inline protected
References OpenSim::MocoDirectCollocationSolver::get_enforce_constraint_derivatives(), OpenSim::Model::getMatterSubsystem(), OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_mocoTropterSolver, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_modelBase, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_numKinematicConstraintEquations, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_pvaerr, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_stateBase, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_total_ma, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_total_mp, and OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_total_mv.
Referenced by OpenSim::MocoTropterSolver::ExplicitTropterProblem< T >::calc_differential_algebraic_equations().
calcPathConstraintErrors()
template<typename T > void OpenSim::MocoTropterSolver::TropterProblemBase< T >::calcPathConstraintErrors (const SimTK::State & state, tropter::Output< T > & out) const inline protected
References OpenSim::MocoProblemRep::calcPathConstraintErrors(), OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_mocoProbRep, and OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_numKinematicConstraintEquations.
Referenced by OpenSim::MocoTropterSolver::ExplicitTropterProblem< T >::calc_differential_algebraic_equations(), and OpenSim::MocoTropterSolver::ImplicitTropterProblem< T >::calc_differential_algebraic_equations().
convertIterateTropterToMoco()
template<typename T > template<typename MocoTrajectoryType , typename tropIterateType > MocoTrajectoryType OpenSim::MocoTropterSolver::TropterProblemBase< T >::convertIterateTropterToMoco (const tropIterateType & tropSol) const
convertToMocoSolution()
template<typename T > MocoSolution OpenSim::MocoTropterSolver::TropterProblemBase< T >::convertToMocoSolution (const tropter::Solution & tropSol) const
convertToMocoTrajectory()
template<typename T > MocoTrajectory OpenSim::MocoTropterSolver::TropterProblemBase< T >::convertToMocoTrajectory (const tropter::Iterate & tropSol) const
convertToTropterIterate()
template<typename T > tropter::Iterate OpenSim::MocoTropterSolver::TropterProblemBase< T >::convertToTropterIterate (const MocoTrajectory & mocoIter) const
initialize_on_iterate()
template<typename T > void OpenSim::MocoTropterSolver::TropterProblemBase< T >::initialize_on_iterate (const Eigen::VectorXd & parameters) const inline final override protected
References OpenSim::MocoTropterSolver::TropterProblemBase< T >::applyParametersToModelProperties(), and OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_fileDeletionThrower.
setSimTKState() [1/2]
template<typename T > void OpenSim::MocoTropterSolver::TropterProblemBase< T >::setSimTKState (const tropter::Input< T > & in) const inline protected
Referenced by OpenSim::MocoTropterSolver::TropterProblemBase< T >::calc_cost_integrand(), OpenSim::MocoTropterSolver::ExplicitTropterProblem< T >::calc_differential_algebraic_equations(), OpenSim::MocoTropterSolver::ImplicitTropterProblem< T >::calc_differential_algebraic_equations(), OpenSim::MocoTropterSolver::TropterProblemBase< T >::setSimTKStateForCostFinal(), and OpenSim::MocoTropterSolver::TropterProblemBase< T >::setSimTKStateForCostInitial().
setSimTKState() [2/2]
template<typename T > void OpenSim::MocoTropterSolver::TropterProblemBase< T >::setSimTKState (const T & time, const Eigen::Ref< const tropter::VectorX< T >> & states, const Eigen::Ref< const tropter::VectorX< T >> & controls, const Eigen::Ref< const tropter::VectorX< T >> & adjuncts, int stateDisConIndex = 0) const inline protected
Use stateDisConIndex to specify which of the two stateDisabledConstraints from MocoProblemRep to update.
References OpenSim::MocoTropterSolver::TropterProblemBase< T >::calcAndApplyKinematicConstraintForces(), OpenSim::MocoProblemRep::getAccelerationMotion(), OpenSim::MocoProblemRep::getDiscreteControllerDisabledConstraints(), OpenSim::MocoProblemRep::isPrescribedKinematics(), OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_implicit, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_mocoProbRep, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_modelControlIndices, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_modelDisabledConstraints, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_numKinematicConstraintEquations, OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_stateBase, OpenSim::MocoTropterSolver::TropterProblemBase< T >::setSimTKTimeAndStates(), OpenSim::AccelerationMotion::setUDot(), OpenSim::DiscreteController::updDiscreteControls(), and OpenSim::MocoProblemRep::updStateDisabledConstraints().
setSimTKStateForCostFinal()
template<typename T > void OpenSim::MocoTropterSolver::TropterProblemBase< T >::setSimTKStateForCostFinal (const tropter::CostInput< T > & in) const inline protected
References OpenSim::MocoTropterSolver::TropterProblemBase< T >::setSimTKState().
Referenced by OpenSim::MocoTropterSolver::TropterProblemBase< T >::calc_cost().
setSimTKStateForCostInitial()
template<typename T > void OpenSim::MocoTropterSolver::TropterProblemBase< T >::setSimTKStateForCostInitial (const tropter::CostInput< T > & in) const inline protected
References OpenSim::MocoTropterSolver::TropterProblemBase< T >::setSimTKState().
Referenced by OpenSim::MocoTropterSolver::TropterProblemBase< T >::calc_cost().
setSimTKTimeAndStates()
template<typename T > void OpenSim::MocoTropterSolver::TropterProblemBase< T >::setSimTKTimeAndStates (const T & time, Eigen::Ref< const tropter::VectorX< T >> states, SimTK::State & simTKState) const inline protected
References OpenSim::MocoTropterSolver::TropterProblemBase< T >::m_yIndexMap.
Referenced by OpenSim::MocoTropterSolver::TropterProblemBase< T >::setSimTKState().
The documentation for this class was generated from the following files:
OpenSim/Moco/MocoTropterSolver.h
OpenSim/Moco/tropter/TropterProblem.h