API: OpenSim::TableSource_< ET > Class Template Reference
OpenSim::TableSource_< ET > Class Template Reference
Component representing a source of data from a TimeSeriesTable_.
OpenSim Properties, Sockets, Outputs, Inputs
Properties (single-value)
std::string filename
"Path to the file to populate the TableSource_ " "with. The path is relative to the working " "directory, not relative to the directory " "containing the model file."
std::string tablename
"Name of the table in the file to populate the " "TableSource with. Ex. 'markers', 'forces'."
Outputs
Vector all_columns
Provides the value of getRowAtTime() and is available at stage SimTK::Stage::Time .
Outputs (list)
ET column
Provides the value of getColumnAtTime() and is available at stage SimTK::Stage::Time .
OpenSim Properties, Sockets, Outputs, Inputs inherited from OpenSim::Component
Component components
"List of components that this component owns and serializes."
Public Member Functions
TableSource_ ()
TableSource_ (const TableSource_ &)=default
TableSource_ (TableSource_ &&)=default
TableSource_ & operator= (const TableSource_ &)=default
TableSource_ & operator= (TableSource_ &&)=default
TableSource_ (const Table &table)
Construct the TableSource_ by giving it a TimeSeriesTable_ to hold.
TableSource_ (const std::string &filename)
Construct the TableSource_ from a file.
TableSource_ (const std::string &filename, const std::string &tablename)
Construct the TableSource_ from a file.
Property-related functions
const std::string & get_filename () const
Get the value of the filename property.
std::string & upd_filename ()
Get a writable reference to the filename property.
void set_filename (const std::string &value)
Set the value of the filename property.
const std::string & get_tablename () const
Get the value of the tablename property.
std::string & upd_tablename ()
Get a writable reference to the tablename property.
void set_tablename (const std::string &value)
Set the value of the tablename property.
Get/Set underlying TimeSeriesTable_
const Table & getTable () const
Get a read-only reference to the TimeSeriesTable_ this TableSource_ currently holds.
void setTable (const Table &table)
Replace the existing TimeSeriesTable_ that this TableSource_ currently holds.
void setTable (const std::string &filename)
Replace the TimeSeriesTable_ that this TableSource_ currently holds.
void setTable (const std::string &filename, const std::string &tablename)
Replace the TimeSeriesTable_ that this TableSource_ currently holds.
Public Member Functions inherited from OpenSim::Component
Component ()
Default constructor.
Component (const std::string &aFileName, bool aUpdateFromXMLNode=true)
Construct Component from an XML file.
Component (SimTK::Xml::Element &aNode)
Construct Component from a specific node in an XML document.
Component (const Component &)=default
Use default copy constructor and assignment operator.
Component & operator= (const Component &)=default
virtual ~Component ()=default
Destructor is virtual to allow concrete Component to cleanup.
virtual void generateDecorations (bool fixed, const ModelDisplayHints &hints, const SimTK::State &state, SimTK::Array_< SimTK::DecorativeGeometry > &appendToThis) const
Optional method for generating arbitrary display geometry that reflects this Component at the specified state.
const SimTK::MultibodySystem & getSystem () const
Get the underlying MultibodySystem that this component is connected to.
bool hasSystem () const
Check if this component has an underlying MultibodySystem.
bool isComponentInOwnershipTree (const Component *component) const
Does the provided component already exist anywhere in the ownership tree (not just subcomponents of this component)?
void addComponent (Component *subcomponent)
Add a Component (as a subcomponent) of this component.
template<typename T = Component>
ComponentList< const T > getComponentList () const
Get an iterator through the underlying subcomponents that this component is composed of.
template<typename T = Component>
ComponentList< T > updComponentList ()
Similar to getComponentList(), except the resulting list allows one to modify the components.
template<typename T = Component>
unsigned countNumComponents () const
Uses getComponentList<T>() to count the number of underlying subcomponents of the specified type.
std::string getAbsolutePathString () const
Get the complete (absolute) pathname for this Component to its ancestral Component, which is the root of the tree to which this Component belongs.
ComponentPath getAbsolutePath () const
Return a ComponentPath of the absolute path of this Component.
std::string getRelativePathString (const Component &wrt) const
Get the relative path of this Component with respect to another Component, as a string.
ComponentPath getRelativePath (const Component &wrt) const
Get the relative path of this Component with respect to another Component.
bool hasComponent (const std::string &pathname) const
Query if there is a component (of any type) at the specified path name.
template<class C = Component>
bool hasComponent (const std::string &pathname) const
Query if there is a component of a given type at the specified path name.
template<class C = Component>
const C & getComponent (const std::string &pathname) const
Get a unique subcomponent of this Component by its path name and type 'C'.
template<class C = Component>
const C & getComponent (const ComponentPath &pathname) const
const Component & getComponent (const std::string &pathname) const
Similar to the templatized getComponent(), except this returns the component as the generic Component type.
template<class C = Component>
C & updComponent (const std::string &name)
Get a writable reference to a subcomponent.
template<class C = Component>
C & updComponent (const ComponentPath &name)
Component & updComponent (const std::string &pathname)
Similar to the templatized updComponent(), except this returns the component as the generic Component type.
unsigned printComponentsMatching (const std::string &substring) const
Print a list to the console of all components whose absolute path name contains the given string.
int getNumStateVariables () const
Get the number of "continuous" state variables maintained by the Component and its subcomponents.
Array< std::string > getStateVariableNames () const
Get the names of "continuous" state variables maintained by the Component and its subcomponents.
template<class C = Component>
const C * findComponent (const ComponentPath &pathToFind) const
Find a Component to which this Component is an ancestor—in other words, a Component that is directly owned by this Component or is owned by one of its sub-components, sub-sub-components, etc.
template<class C = Component>
const C * findComponent (const std::string &pathToFind) const
Same as findComponent(const ComponentPath&), but accepting a string (a path or just a name) as input.
const StateVariable * traverseToStateVariable (const std::string &pathName) const
Get a StateVariable anywhere in the Component tree, given a StateVariable path.
const StateVariable * traverseToStateVariable (const ComponentPath &path) const
Get a StateVariable anywhere in the Component tree, given a StateVariable path.
void finalizeFromProperties ()
Define a Component's internal data members and structure according to its properties.
void finalizeConnections (Component &root)
Satisfy the Component's connections specified by its Sockets and Inputs.
void clearConnections ()
Disconnect/clear this Component from its aggregate component.
void addToSystem (SimTK::MultibodySystem &system) const
Have the Component add itself to the underlying computational System.
void initStateFromProperties (SimTK::State &state) const
Initialize Component's state variable values from its properties.
void setPropertiesFromState (const SimTK::State &state)
Set Component's properties given a state.
int getNumSockets () const
Get the number of Sockets in this Component.
std::vector< std::string > getSocketNames () const
Collect and return the names of the sockets in this component.
template<typename T >
const T & getConnectee (const std::string &name) const
Get the "connectee" object that the Component's Socket is bound to.
const Object & getConnectee (const std::string &name) const
Get the connectee as an Object.
const AbstractSocket & getSocket (const std::string &name) const
Get an AbstractSocket for the given socket name.
AbstractSocket & updSocket (const std::string &name)
Get a writable reference to the AbstractSocket for the given socket name.
template<typename T >
const Socket< T > & getSocket (const std::string &name) const
Get a const reference to the concrete Socket provided by this Component by name.
template<typename T >
Socket< T > & updSocket (const std::string &name)
Get a writable reference to the concrete Socket provided by this Component by name.
void printSubcomponentInfo () const
List all subcomponents by name and recurse into these components to list their subcomponents, and so on.
void printSocketInfo () const
List all the Sockets of this component and whether or not they are connected.
void printInputInfo () const
List all the inputs of this component and whether or not they are connected.
template<typename C >
void printSubcomponentInfo () const
void printOutputInfo (const bool includeDescendants=true) const
Print outputs of this component and optionally, those of all subcomponents.
int getNumInputs () const
Access the number of Inputs that this component has.
int getNumOutputs () const
Access the number of Outputs that this component has.
std::vector< std::string > getInputNames () const
Collect and return the names of Inputs in this component as an std::vector.
std::vector< std::string > getOutputNames () const
Collect and return the names of Outputs in this component as an std::vector.
const AbstractInput & getInput (const std::string &name) const
Get an Input provided by this Component by name.
AbstractInput & updInput (const std::string &name)
Get a writable reference to an Input provided by this Component by name.
template<typename T >
const Input< T > & getInput (const std::string &name) const
Get a concrete Input that you can directly ask for its values.
const AbstractOutput & getOutput (const std::string &name) const
Get the Output provided by this Component by name.
AbstractOutput & updOutput (const std::string &name)
Get a writable reference to an Output provided by this Component by name.
SimTK::IteratorRange< OutputConstIterator > getOutputs () const
Iterate through all Outputs of this component.
int getModelingOption (const SimTK::State &state, const std::string &name) const
Get a ModelingOption flag for this Component by name.
void setModelingOption (SimTK::State &state, const std::string &name, int flag) const
Set the value of a ModelingOption flag for this Component.
template<typename T >
const T & getInputValue (const SimTK::State &state, const std::string &name) const
Get the Input value that this component is dependent on.
template<typename T >
const T & getOutputValue (const SimTK::State &state, const std::string &name) const
Get the Output value provided by this Component by name.
double getStateVariableValue (const SimTK::State &state, const std::string &name) const
Get the value of a state variable allocated by this Component.
double getStateVariableValue (const SimTK::State &state, const ComponentPath &path) const
Get the value of a state variable allocated by this Component.
void setStateVariableValue (SimTK::State &state, const std::string &name, double value) const
Set the value of a state variable allocated by this Component by name.
SimTK::Vector getStateVariableValues (const SimTK::State &state) const
Get all values of the state variables allocated by this Component.
void setStateVariableValues (SimTK::State &state, const SimTK::Vector &values) const
Set all values of the state variables allocated by this Component.
double getStateVariableDerivativeValue (const SimTK::State &state, const std::string &name) const
Get the value of a state variable derivative computed by this Component.
double getDiscreteVariableValue (const SimTK::State &state, const std::string &name) const
Get the value of a discrete variable allocated by this Component by name.
void setDiscreteVariableValue (SimTK::State &state, const std::string &name, double value) const
Set the value of a discrete variable allocated by this Component by name.
template<class T >
SimTK::CacheEntryIndex getCacheVariableIndex (const CacheVariable< T > &cv) const
Get the index of a Component's cache variable in the Subsystem for allocations.
SimTK::CacheEntryIndex getCacheVariableIndex (const std::string &name) const
Get the index of a Component's cache variable in the Subsystem for allocations.
template<class T >
const T & getCacheVariableValue (const SimTK::State &state, const std::string &name) const
Get the value of a cache variable allocated by this Component by name.
template<class T >
const T & getCacheVariableValue (const SimTK::State &state, const CacheVariable< T > &cv) const
Get the value of a cache variable allocated by this Component.
template<typename T >
void setCacheVariableValue (const SimTK::State &state, const std::string &k, T value) const
Set the value of a cache variable, identified by name, to a new value and mark the cache variable as valid.
template<typename T >
void setCacheVariableValue (const SimTK::State &state, const CacheVariable< T > &cv, T value) const
Set the value of a cache variable to a new value and mark the cache variable as valid.
template<typename T >
T & updCacheVariableValue (const SimTK::State &state, const std::string &name) const
Returns a mutable reference to the value of a cache variable identified by name.
template<typename T >
T & updCacheVariableValue (const SimTK::State &state, const CacheVariable< T > &cv) const
Returns a mutable reference to the value of a cache variable.
bool isCacheVariableValid (const SimTK::State &state, const std::string &name) const
Returns true if the cache variable, identified by name, is valid.
template<class T >
bool isCacheVariableValid (const SimTK::State &state, const CacheVariable< T > &cv) const
Returns true if the cache variable is valid.
void markCacheVariableValid (const SimTK::State &state, const std::string &name) const
Marks the value of a cache variable, identified by name, as valid.
template<typename T >
void markCacheVariableValid (const SimTK::State &state, const CacheVariable< T > &cv) const
Marks the value of a cache variable as valid.
void markCacheVariableInvalid (const SimTK::State &state, const std::string &name) const
Marks the value of a cache variable, identified by name, as invalid.
template<class T >
void markCacheVariableInvalid (const SimTK::State &state, const CacheVariable< T > &cv) const
Marks the value of a cache variable as invalid.
const Component & getOwner () const
Access the owner of this Component.
bool hasOwner () const
(For advanced users) Check if this Component has an owner.
const Component & getRoot () const
Obtain the root Component, which is this component if it is orphaned.
Public Member Functions inherited from OpenSim::Object
virtual ~Object ()
Virtual destructor for cleanup.
bool isEqualTo (const Object &aObject) const
Equality operator wrapper for use from languages not supporting operator overloading.
Object & operator= (const Object &aObject)
Copy assignment copies he base class fields, including the properties.
virtual bool operator== (const Object &aObject) const
Determine if two objects are equal.
virtual bool operator< (const Object &aObject) const
Provide an ordering for objects so they can be put in sorted containers.
void setName (const std::string &name)
Set the name of the Object.
const std::string & getName () const
Get the name of this Object.
void setDescription (const std::string &description)
Set description, a one-liner summary.
const std::string & getDescription () const
Get description, a one-liner summary.
const std::string & getAuthors () const
Get Authors of this Object.
void setAuthors (const std::string &authors)
Set Authors of this object.
const std::string & getReferences () const
Get references or publications to cite if using this object.
void setReferences (const std::string &references)
Set references or publications to cite if using this object.
int getNumProperties () const
Determine how many properties are stored with this Object.
const AbstractProperty & getPropertyByIndex (int propertyIndex) const
Get a const reference to a property by its index number, returned as an AbstractProperty.
AbstractProperty & updPropertyByIndex (int propertyIndex)
Get a writable reference to a property by its index number, returned as an AbstractProperty.
bool hasProperty (const std::string &name) const
Return true if this Object has a property of any type with the given name, which must not be empty.
const AbstractProperty & getPropertyByName (const std::string &name) const
Get a const reference to a property by its name, returned as an AbstractProperty.
AbstractProperty & updPropertyByName (const std::string &name)
Get a writable reference to a property by its name, returned as an AbstractProperty.
template<class T >
bool hasProperty () const
Return true if this Object contains an unnamed, one-object property that contains objects of the given template type T.
template<class T >
const Property< T > & getProperty (const PropertyIndex &index) const
Get property of known type Property<T> as a const reference; the property must be present and have the right type.
template<class T >
const Property< T > & getPropertyByName (const std::string &name) const
template<class T >
Property< T > & updProperty (const PropertyIndex &index)
Get property of known type Property<T> as a writable reference; the property must be present and have the right type.
template<class T >
Property< T > & updPropertyByName (const std::string &name)
Get property of known type Property<T> as a writable reference; the property must be present and have the right type.
bool isObjectUpToDateWithProperties () const
Returns true if no property's value has changed since the last time setObjectIsUpToDateWithProperties() was called.
void readObjectFromXMLNodeOrFile (SimTK::Xml::Element &objectElement, int versionNumber)
We're given an XML element from which we are to populate this Object.
void updateXMLNode (SimTK::Xml::Element &parent, const AbstractProperty *prop=nullptr) const
Serialize this object into the XML node that represents it.
bool getInlined () const
Inlined means an in-memory Object that is not associated with an XMLDocument.
void setInlined (bool aInlined, const std::string &aFileName="")
Mark this as inlined or not and optionally provide a file name to associate with the new XMLDocument for the non-inline case.
std::string getDocumentFileName () const
If there is a document associated with this object then return the file name maintained by the document.
int getDocumentFileVersion () const
If there is a document associated with this object then return its version number.
void setAllPropertiesUseDefault (bool aUseDefault)
bool print (const std::string &fileName) const
Write this Object into an XML file of the given name; conventionally the suffix to use is ".osim".
std::string dump () const
dump the XML representation of this Object into an std::string and return it.
virtual bool isA (const char *type) const
The default implementation returns true only if the supplied string is "Object"; each Object-derived class overrides this to match its own class name.
const std::string & toString () const
Wrapper to be used on Java side to display objects in tree; this returns just the object's name.
PropertySet & getPropertySet ()
OBSOLETE: Get a reference to the PropertySet maintained by the Object.
const PropertySet & getPropertySet () const
Auto-generated functions
static TableSource_ * safeDownCast (OpenSim::Object *obj)
For use in MATLAB and Python to access the concrete class.
static const std::string & getClassName ()
This returns "TableSource__<T>_".
TableSource_ * clone () const override
Create a new heap-allocated copy of the concrete object to which this Object refers.
const std::string & getConcreteClassName () const override
Returns the class name of the concrete Object-derived class of the actual object referenced by this Object, as a string.
Additional Inherited Members
Static Public Member Functions inherited from OpenSim::Component
static Component * safeDownCast (OpenSim::Object *obj)
For use in MATLAB and Python to access the concrete class.
static const std::string & getClassName ()
This returns "Component".
Static Public Member Functions inherited from OpenSim::Object
static void registerType (const Object &defaultObject)
Register an instance of a class; if the class is already registered it will be replaced.
static void renameType (const std::string &oldTypeName, const std::string &newTypeName)
Support versioning by associating the current Object type with an old name.
static const Object * getDefaultInstanceOfType (const std::string &concreteClassName)
Return a pointer to the default instance of the registered (concrete) Object whose class name is given, or NULL if the type is not registered.
template<class T >
static bool isObjectTypeDerivedFrom (const std::string &concreteClassName)
Return true if the given concrete object type represents a subclass of the template object type T, and thus could be referenced with a T*.
static Object * newInstanceOfType (const std::string &concreteClassName)
Create a new instance of the concrete Object type whose class name is given as concreteClassName.
static void getRegisteredTypenames (Array< std::string > &typeNames)
Retrieve all the typenames registered so far.
template<class T >
static void getRegisteredObjectsOfGivenType (ArrayPtrs< T > &rArray)
Return an array of pointers to the default instances of all registered (concrete) Object types that derive from a given Object-derived type that does not have to be concrete.
static bool PrintPropertyInfo (std::ostream &os, const std::string &classNameDotPropertyName, bool printFlagInfo=true)
Dump formatted property information to a given output stream, useful for creating a "help" facility for registered objects.
static bool PrintPropertyInfo (std::ostream &os, const std::string &className, const std::string &propertyName, bool printFlagInfo=true)
Same as the other signature but the class name and property name are provided as two separate strings.
static Object * makeObjectFromFile (const std::string &fileName)
Create an OpenSim object whose type is based on the tag at the root node of the XML file passed in.
static const std::string & getClassName ()
Return the name of this class as a string; i.e., "Object".
static void setSerializeAllDefaults (bool shouldSerializeDefaults)
Static function to control whether all registered objects and their properties are written to the defaults section of output files rather than only those values for which the default was explicitly overwritten when read in from an input file or set programmatically.
static bool getSerializeAllDefaults ()
Report the value of the "serialize all defaults" flag.
static bool isKindOf (const char *type)
Returns true if the passed-in string is "Object"; each Object-derived class defines a method of this name for its own class name.
static void setDebugLevel (int newLevel)
Set the amount of logging output.
static int getDebugLevel ()
Get the current setting of debug level.
static Object * SafeCopy (const Object *aObject)
Use the clone() method to duplicate the given object unless the pointer is null in which case null is returned.
static void RegisterType (const Object &defaultObject)
OBSOLETE alternate name for registerType().
static void RenameType (const std::string &oldName, const std::string &newName)
OBSOLETE alternate name for renameType().
Detailed Description
template<typename ET>
class OpenSim::TableSource_< ET >
Component representing a source of data from a TimeSeriesTable_.
This Component has two outputs:
A list output with one channel per column of the TimeSeriesTable_.
A non-list output for a row of the TimeSeriesTable_.
Construct this Component by giving it a TimeSeriesTable_. Then use it by connecting its output to the Input of another Component that accepts compatible type of Input. Make sure to populate the column-labels of the TimeSeriesTable_ before connecting this Component to the input of another Component.
Template Parameters
ET Type of each element of the TimeSeriesTable_ this Component represents.
Constructor & Destructor Documentation
TableSource_() [1/6]
template<typename ET > OpenSim::TableSource_< ET >::TableSource_ () inline
TableSource_() [2/6]
template<typename ET > OpenSim::TableSource_< ET >::TableSource_ (const TableSource_< ET > &) default
TableSource_() [3/6]
template<typename ET > OpenSim::TableSource_< ET >::TableSource_ (TableSource_< ET > &&) default
TableSource_() [4/6]
template<typename ET > OpenSim::TableSource_< ET >::TableSource_ (const Table & table) inline
Construct the TableSource_ by giving it a TimeSeriesTable_ to hold.
TableSource_() [5/6]
template<typename ET > OpenSim::TableSource_< ET >::TableSource_ (const std::string & filename) inline
Construct the TableSource_ from a file.
Parameters
filename Name of the file.
Exceptions
KeyNotFound If table provided does not have column-labels.
References OpenSim::TableSource_< ET >::filename.
TableSource_() [6/6]
template<typename ET > OpenSim::TableSource_< ET >::TableSource_ (const std::string & filename, const std::string & tablename) inline
Construct the TableSource_ from a file.
Parameters
filename Name of the file.
tablename Name of the table in the file to populate the TableSource with. Ex. 'markers', 'forces'.
Exceptions
KeyNotFound If table provided does not have column-labels.
References OpenSim::TableSource_< ET >::filename, OpenSim::TableSource_< ET >::setTable(), and OpenSim::TableSource_< ET >::tablename.
Member Typedef Documentation
Table
template<typename ET > typedef TimeSeriesTable_<ET> OpenSim::TableSource_< ET >::Table
Type of the TimeSeriesTable_ this Component will hold.
Vector
template<typename ET > typedef SimTK::Vector_<ET> OpenSim::TableSource_< ET >::Vector
Type of the 'row' Output of this Component.
Member Function Documentation
clone()
template<typename ET > TableSource_* OpenSim::TableSource_< ET >::clone () const inline override virtual
Create a new heap-allocated copy of the concrete object to which this Object refers.
It is up to the caller to delete the returned object when no longer needed. Every concrete object deriving from Object implements this pure virtual method automatically, via the declaration macro it invokes (e.g., OpenSim_DECLARE_CONCRETE_OBJECT()). Note that the concrete class overrides modify the return type to be a pointer to the concrete object; that still overrides the base class method because the return type is covariant with (that is, derives from) Object.
Implements OpenSim::Component.
get_filename()
template<typename ET > const std::string& OpenSim::TableSource_< ET >::get_filename () const inline
Get the value of the filename property.
get_tablename()
template<typename ET > const std::string& OpenSim::TableSource_< ET >::get_tablename () const inline
Get the value of the tablename property.
getClassName()
template<typename ET > static const std::string& OpenSim::TableSource_< ET >::getClassName () inline static
This returns "TableSource__<T>_".
T is the template argument for this class. See getConcreteClassName() if you want the class name of the underlying concrete object instead.
getColumnAtTime()
template<typename ET > ET OpenSim::TableSource_< ET >::getColumnAtTime (const SimTK::State & state, const std::string & columnLabel) const inline protected
Retrieve value of a column at a given time(implicit in the State provided).
Linear interpolation is performed if the TimeSeriesTable_ does not contain an entry for the time mentioned by the state.
Exceptions
EmptyTable If the TimeSeriesTable_ this TableSource_ holds is currently empty.
TimeOutOfRange If the time specified by the State is either less than the smallest timestamp or greater than the largest timestamp in the TimeSeriesTable_.
KeyNotFound If TimeSeriesTable_ does not have column-labels.
References OpenSim::AbstractDataTable::getColumnIndex(), OpenSim::DataTable_< ETX, ETY >::getIndependentColumn(), OpenSim::DataTable_< ETX, ETY >::getMatrix(), and OpenSim::AbstractDataTable::getNumRows().
getConcreteClassName()
template<typename ET > const std::string& OpenSim::TableSource_< ET >::getConcreteClassName () const inline override virtual
Returns the class name of the concrete Object-derived class of the actual object referenced by this Object, as a string.
This is the string that is used as the tag for this concrete object in an XML file. Every concrete class derived from Object automatically overrides this method via the declaration macro it uses. See getClassName() to get the class name of the referencing (possibly abstract) class rather than the concrete object.
See also
getClassName()
Implements OpenSim::Component.
getRowAtTime()
template<typename ET > Vector OpenSim::TableSource_< ET >::getRowAtTime (const SimTK::State & state) const inline protected
Retrieve a row of the TimeSeriesTable_ at a given time (specified by the state).
Linear interpolation is performed if the TimeSeriesTable_ does not have an entry for the time mentioned by the state.
Exceptions
EmptyTable If the TimeSeriesTable_ this TableSource_ holds is currently empty.
TimeOutOfRange If the time specified by the State is either less than the smallest timestamp or greater than the largest timestamp in the TimeSeriesTable_.
References OpenSim::DataTable_< ETX, ETY >::getIndependentColumn(), OpenSim::AbstractDataTable::getNumRows(), and OpenSim::DataTable_< ETX, ETY >::getRowAtIndex().
getTable()
template<typename ET > const Table& OpenSim::TableSource_< ET >::getTable () const inline
Get a read-only reference to the TimeSeriesTable_ this TableSource_ currently holds.
operator=() [1/2]
template<typename ET > TableSource_& OpenSim::TableSource_< ET >::operator= (const TableSource_< ET > &) default
operator=() [2/2]
template<typename ET > TableSource_& OpenSim::TableSource_< ET >::operator= (TableSource_< ET > &&) default
safeDownCast()
template<typename ET > static TableSource_* OpenSim::TableSource_< ET >::safeDownCast (OpenSim::Object * obj) inline static
For use in MATLAB and Python to access the concrete class.
Example: cObj = TableSource_.safeDownCast(obj). This is equivalent to dynamic_cast<TableSource_*>(obj) in C++.
set_filename()
template<typename ET > void OpenSim::TableSource_< ET >::set_filename (const std::string & value) inline
Set the value of the filename property.
Referenced by OpenSim::TableSource_< ET >::setTable().
set_tablename()
template<typename ET > void OpenSim::TableSource_< ET >::set_tablename (const std::string & value) inline
Set the value of the tablename property.
Referenced by OpenSim::TableSource_< ET >::setTable().
setTable() [1/3]
template<typename ET > void OpenSim::TableSource_< ET >::setTable (const Table & table) inline
Replace the existing TimeSeriesTable_ that this TableSource_ currently holds.
The properties 'filename' and 'tablename' are reset to empty strings as a result of this operation.
Exceptions
KeyNotFound If table provided does not have column labels.
References OpenSim::TableSource_< ET >::set_filename(), OpenSim::TableSource_< ET >::set_tablename(), and OpenSim::TableSource_< ET >::setTable_impl().
Referenced by OpenSim::TableSource_< ET >::TableSource_().
setTable() [2/3]
template<typename ET > void OpenSim::TableSource_< ET >::setTable (const std::string & filename) inline
Replace the TimeSeriesTable_ that this TableSource_ currently holds.
Property 'filename' is reset to the value provided. Property 'tablename' is reset to the empty string as a result of this operation.
Exceptions
InvalidCall If property filename is set. This call is not allowed if filename property is set.
KeyNotFound If table provided does not have column labels.
References OpenSim::TableSource_< ET >::filename, OpenSim::TableSource_< ET >::set_filename(), OpenSim::TableSource_< ET >::set_tablename(), and OpenSim::TableSource_< ET >::setTable_impl().
setTable() [3/3]
template<typename ET > void OpenSim::TableSource_< ET >::setTable (const std::string & filename, const std::string & tablename) inline
Replace the TimeSeriesTable_ that this TableSource_ currently holds.
Properties 'filename' and 'tablename' are reset to the values provided.
Parameters
filename Name of the file.
tablename Name of the table in the file to construct the TimeSeriesTable_ from. For example, a c3d file contains tables named 'markers' and 'forces'.
Exceptions
InvalidCall If property filename is set. This call is not allowed if filename property is set.
KeyNotFound If table provided does not have column labels.
References OpenSim::TableSource_< ET >::filename, OpenSim::TableSource_< ET >::set_filename(), OpenSim::TableSource_< ET >::set_tablename(), OpenSim::TableSource_< ET >::setTable_impl(), and OpenSim::TableSource_< ET >::tablename.
setTable_impl()
template<typename ET > void OpenSim::TableSource_< ET >::setTable_impl (const Table & table) inline protected
References OpenSim::AbstractDataTable::getColumnLabels(), and OpenSim::Component::updOutput().
Referenced by OpenSim::TableSource_< ET >::setTable().
upd_filename()
template<typename ET > std::string& OpenSim::TableSource_< ET >::upd_filename () inline
Get a writable reference to the filename property.
upd_tablename()
template<typename ET > std::string& OpenSim::TableSource_< ET >::upd_tablename () inline
Get a writable reference to the tablename property.
OpenSim Property, Socket, Output, Input Documentation
all_columns
template<typename ET > Vector OpenSim::TableSource_< ET >::all_columns
Provides the value of getRowAtTime() and is available at stage SimTK::Stage::Time .
This output was generated with the OpenSim_DECLARE_OUTPUT macro.
column
template<typename ET > ET OpenSim::TableSource_< ET >::column
Provides the value of getColumnAtTime() and is available at stage SimTK::Stage::Time .
This output can have multiple channels. TODO This output was generated with the OpenSim_DECLARE_LIST_OUTPUT macro.
filename
template<typename ET > std::string OpenSim::TableSource_< ET >::filename
"Path to the file to populate the TableSource_ " "with. The path is relative to the working " "directory, not relative to the directory " "containing the model file."
This property appears in XML files under the tag <filename>. This property was generated with the OpenSim_DECLARE_PROPERTY macro; see Property to learn about the property system.
See also
get_filename(), upd_filename(), set_filename()
Referenced by OpenSim::TableSource_< ET >::setTable(), and OpenSim::TableSource_< ET >::TableSource_().
tablename
template<typename ET > std::string OpenSim::TableSource_< ET >::tablename
"Name of the table in the file to populate the " "TableSource with. Ex. 'markers', 'forces'."
This property appears in XML files under the tag <tablename>. This property was generated with the OpenSim_DECLARE_PROPERTY macro; see Property to learn about the property system.
See also
get_tablename(), upd_tablename(), set_tablename()
Referenced by OpenSim::TableSource_< ET >::setTable(), and OpenSim::TableSource_< ET >::TableSource_().
The documentation for this class was generated from the following file:
OpenSim/Common/TableSource.h