API: OpenSim::TransformAxis Class Reference
OpenSim::TransformAxis Class Reference
A class expressing a transformation of a child body in relation to a parent body along either a translation or about a rotation axis.
OpenSim Properties, Sockets, Outputs, Inputs
Properties (list)
The "coordinates" property holds a list of strings representing the generalized coordinate names that serve as the independent variables of the transform function.
std::string coordinates
"Names of the coordinates that serve as the independent variables \ of the transform function."
Properties (single-value)
The "function" property holds the transform function of the generalized coordinate(s) used to represent the amount of displacement about/along the specified axis.
If none is specified a Constant function is applied.
SimTK::Vec3 axis
"Rotation or translation axis for the transform."
Function function
"Transform function of the generalized coordinates used to \ represent the amount of displacement along a specified axis."
Public Member Functions
TransformAxis ()
TransformAxis (const Array< std::string > &coordNames, const SimTK::Vec3 &axis)
TransformAxis (SimTK::Xml::Element &node)
void setCoordinateNames (const Array< std::string > &coordNames)
Set the names of the generalized coordinates that affect the motion along the axis controlled by this TransformAxis object.
const Property< std::string > & getCoordinateNames () const
Get the generalized coordinate names associated with this object.
Array< std::string > getCoordinateNamesInArray () const
Copy the coordinate names into an OpenSim::Array for convenience.
void setAxis (const SimTK::Vec3 &axis)
Set the value of the "axis" property.
const SimTK::Vec3 & getAxis () const
Return the current value of the "axis" property.
void getAxis (SimTK::Vec3 &axis) const
Alternate signature that writes the axis value to its argument.
double getAxis (int which) const
Get one component (0,1, or 2) of the axis vector.
bool hasFunction () const
Determine whether a custom function has been specified to map between the generalized coordinate and the amount of transformation along the specified axis.
const Function & getFunction () const
Get the custom function that maps between the generalized coordinates and the amount of displacement along the specified axis.
Function & updFunction ()
Get writable access to the transform function.
void setFunction (Function *function)
Set the custom function that maps between the generalized coordinates and the amount of displacement about/along the specified axis.
void setFunction (const Function &function)
Set the custom function that maps between the generalized coordinates and the amount of transformation about/along the specified axis.
const Joint & getJoint () const
Return a reference to the Joint to which this TransformAxis applies.
double getValue (const SimTK::State &s)
void connectToJoint (const Joint &owningJoint)
Connect the TransformAxis to its owning Joint after the model has been deserialized or copied.
Property-related functions
const std::string & get_coordinates (int i) const
Get the value of the i-th element of the coordinates property.
std::string & upd_coordinates (int i)
Get a writable reference to the i-th element of the coordinates property.
void set_coordinates (int i, const std::string &value)
Set the value of the i-th element of coordinates property.
int append_coordinates (const std::string &value)
Append an element to the coordinates property.
const SimTK::Vec3 & get_axis () const
Get the value of the axis property.
SimTK::Vec3 & upd_axis ()
Get a writable reference to the axis property.
void set_axis (const SimTK::Vec3 &value)
Set the value of the axis property.
const Function & get_function () const
Get the value of the function property.
Function & upd_function ()
Get a writable reference to the function property.
void set_function (const Function &value)
Set the value of the function property.
Public Member Functions inherited from OpenSim::Object
virtual ~Object ()
Virtual destructor for cleanup.
bool isEqualTo (const Object &aObject) const
Equality operator wrapper for use from languages not supporting operator overloading.
Object & operator= (const Object &aObject)
Copy assignment copies he base class fields, including the properties.
virtual bool operator== (const Object &aObject) const
Determine if two objects are equal.
virtual bool operator< (const Object &aObject) const
Provide an ordering for objects so they can be put in sorted containers.
void setName (const std::string &name)
Set the name of the Object.
const std::string & getName () const
Get the name of this Object.
void setDescription (const std::string &description)
Set description, a one-liner summary.
const std::string & getDescription () const
Get description, a one-liner summary.
const std::string & getAuthors () const
Get Authors of this Object.
void setAuthors (const std::string &authors)
Set Authors of this object.
const std::string & getReferences () const
Get references or publications to cite if using this object.
void setReferences (const std::string &references)
Set references or publications to cite if using this object.
int getNumProperties () const
Determine how many properties are stored with this Object.
const AbstractProperty & getPropertyByIndex (int propertyIndex) const
Get a const reference to a property by its index number, returned as an AbstractProperty.
AbstractProperty & updPropertyByIndex (int propertyIndex)
Get a writable reference to a property by its index number, returned as an AbstractProperty.
bool hasProperty (const std::string &name) const
Return true if this Object has a property of any type with the given name, which must not be empty.
const AbstractProperty & getPropertyByName (const std::string &name) const
Get a const reference to a property by its name, returned as an AbstractProperty.
AbstractProperty & updPropertyByName (const std::string &name)
Get a writable reference to a property by its name, returned as an AbstractProperty.
template<class T >
bool hasProperty () const
Return true if this Object contains an unnamed, one-object property that contains objects of the given template type T.
template<class T >
const Property< T > & getProperty (const PropertyIndex &index) const
Get property of known type Property<T> as a const reference; the property must be present and have the right type.
template<class T >
const Property< T > & getPropertyByName (const std::string &name) const
template<class T >
Property< T > & updProperty (const PropertyIndex &index)
Get property of known type Property<T> as a writable reference; the property must be present and have the right type.
template<class T >
Property< T > & updPropertyByName (const std::string &name)
Get property of known type Property<T> as a writable reference; the property must be present and have the right type.
bool isObjectUpToDateWithProperties () const
Returns true if no property's value has changed since the last time setObjectIsUpToDateWithProperties() was called.
void readObjectFromXMLNodeOrFile (SimTK::Xml::Element &objectElement, int versionNumber)
We're given an XML element from which we are to populate this Object.
void updateXMLNode (SimTK::Xml::Element &parent, const AbstractProperty *prop=nullptr) const
Serialize this object into the XML node that represents it.
bool getInlined () const
Inlined means an in-memory Object that is not associated with an XMLDocument.
void setInlined (bool aInlined, const std::string &aFileName="")
Mark this as inlined or not and optionally provide a file name to associate with the new XMLDocument for the non-inline case.
std::string getDocumentFileName () const
If there is a document associated with this object then return the file name maintained by the document.
int getDocumentFileVersion () const
If there is a document associated with this object then return its version number.
void setAllPropertiesUseDefault (bool aUseDefault)
bool print (const std::string &fileName) const
Write this Object into an XML file of the given name; conventionally the suffix to use is ".osim".
std::string dump () const
dump the XML representation of this Object into an std::string and return it.
virtual bool isA (const char *type) const
The default implementation returns true only if the supplied string is "Object"; each Object-derived class overrides this to match its own class name.
const std::string & toString () const
Wrapper to be used on Java side to display objects in tree; this returns just the object's name.
PropertySet & getPropertySet ()
OBSOLETE: Get a reference to the PropertySet maintained by the Object.
const PropertySet & getPropertySet () const
Auto-generated functions
static TransformAxis * safeDownCast (OpenSim::Object *obj)
For use in MATLAB and Python to access the concrete class.
static const std::string & getClassName ()
This returns "TransformAxis".
TransformAxis * clone () const override
Create a new heap-allocated copy of the concrete object to which this Object refers.
const std::string & getConcreteClassName () const override
Returns the class name of the concrete Object-derived class of the actual object referenced by this Object, as a string.
Additional Inherited Members
Static Public Member Functions inherited from OpenSim::Object
static void registerType (const Object &defaultObject)
Register an instance of a class; if the class is already registered it will be replaced.
static void renameType (const std::string &oldTypeName, const std::string &newTypeName)
Support versioning by associating the current Object type with an old name.
static const Object * getDefaultInstanceOfType (const std::string &concreteClassName)
Return a pointer to the default instance of the registered (concrete) Object whose class name is given, or NULL if the type is not registered.
template<class T >
static bool isObjectTypeDerivedFrom (const std::string &concreteClassName)
Return true if the given concrete object type represents a subclass of the template object type T, and thus could be referenced with a T*.
static Object * newInstanceOfType (const std::string &concreteClassName)
Create a new instance of the concrete Object type whose class name is given as concreteClassName.
static void getRegisteredTypenames (Array< std::string > &typeNames)
Retrieve all the typenames registered so far.
template<class T >
static void getRegisteredObjectsOfGivenType (ArrayPtrs< T > &rArray)
Return an array of pointers to the default instances of all registered (concrete) Object types that derive from a given Object-derived type that does not have to be concrete.
static bool PrintPropertyInfo (std::ostream &os, const std::string &classNameDotPropertyName, bool printFlagInfo=true)
Dump formatted property information to a given output stream, useful for creating a "help" facility for registered objects.
static bool PrintPropertyInfo (std::ostream &os, const std::string &className, const std::string &propertyName, bool printFlagInfo=true)
Same as the other signature but the class name and property name are provided as two separate strings.
static Object * makeObjectFromFile (const std::string &fileName)
Create an OpenSim object whose type is based on the tag at the root node of the XML file passed in.
static const std::string & getClassName ()
Return the name of this class as a string; i.e., "Object".
static void setSerializeAllDefaults (bool shouldSerializeDefaults)
Static function to control whether all registered objects and their properties are written to the defaults section of output files rather than only those values for which the default was explicitly overwritten when read in from an input file or set programmatically.
static bool getSerializeAllDefaults ()
Report the value of the "serialize all defaults" flag.
static bool isKindOf (const char *type)
Returns true if the passed-in string is "Object"; each Object-derived class defines a method of this name for its own class name.
static void setDebugLevel (int newLevel)
Set the amount of logging output.
static int getDebugLevel ()
Get the current setting of debug level.
static Object * SafeCopy (const Object *aObject)
Use the clone() method to duplicate the given object unless the pointer is null in which case null is returned.
static void RegisterType (const Object &defaultObject)
OBSOLETE alternate name for registerType().
static void RenameType (const std::string &oldName, const std::string &newName)
OBSOLETE alternate name for renameType().
Detailed Description
A class expressing a transformation of a child body in relation to a parent body along either a translation or about a rotation axis.
The TransformAxis function specified the spatial displacement that is achieved as a function of the generalized coordinate(s).
Author
Peter Loan, Frank C. Anderson, Jeffrey A. Reinbolt, Ajay Seth, Michael Sherman
Constructor & Destructor Documentation
TransformAxis() [1/3]
OpenSim::TransformAxis::TransformAxis ()
TransformAxis() [2/3]
OpenSim::TransformAxis::TransformAxis (const Array< std::string > & coordNames, const SimTK::Vec3 & axis)
TransformAxis() [3/3]
OpenSim::TransformAxis::TransformAxis (SimTK::Xml::Element & node) explicit
Member Function Documentation
append_coordinates()
int OpenSim::TransformAxis::append_coordinates (const std::string & value) inline
Append an element to the coordinates property.
clone()
TransformAxis* OpenSim::TransformAxis::clone () const inline override virtual
Create a new heap-allocated copy of the concrete object to which this Object refers.
It is up to the caller to delete the returned object when no longer needed. Every concrete object deriving from Object implements this pure virtual method automatically, via the declaration macro it invokes (e.g., OpenSim_DECLARE_CONCRETE_OBJECT()). Note that the concrete class overrides modify the return type to be a pointer to the concrete object; that still overrides the base class method because the return type is covariant with (that is, derives from) Object.
Implements OpenSim::Object.
connectToJoint()
void OpenSim::TransformAxis::connectToJoint (const Joint & owningJoint)
Connect the TransformAxis to its owning Joint after the model has been deserialized or copied.
get_axis()
const SimTK::Vec3& OpenSim::TransformAxis::get_axis () const inline
Get the value of the axis property.
get_coordinates()
const std::string& OpenSim::TransformAxis::get_coordinates (int i) const inline
Get the value of the i-th element of the coordinates property.
get_function()
const Function& OpenSim::TransformAxis::get_function () const inline
Get the value of the function property.
getAxis() [1/3]
const SimTK::Vec3& OpenSim::TransformAxis::getAxis () const inline
Return the current value of the "axis" property.
getAxis() [2/3]
void OpenSim::TransformAxis::getAxis (SimTK::Vec3 & axis) const inline
Alternate signature that writes the axis value to its argument.
References getAxis().
Referenced by getAxis().
getAxis() [3/3]
double OpenSim::TransformAxis::getAxis (int which) const inline
Get one component (0,1, or 2) of the axis vector.
getClassName()
static const std::string& OpenSim::TransformAxis::getClassName () inline static
This returns "TransformAxis".
See getConcreteClassName() if you want the class name of the underlying concrete object instead.
getConcreteClassName()
const std::string& OpenSim::TransformAxis::getConcreteClassName () const inline override virtual
Returns the class name of the concrete Object-derived class of the actual object referenced by this Object, as a string.
This is the string that is used as the tag for this concrete object in an XML file. Every concrete class derived from Object automatically overrides this method via the declaration macro it uses. See getClassName() to get the class name of the referencing (possibly abstract) class rather than the concrete object.
See also
getClassName()
Implements OpenSim::Object.
getCoordinateNames()
const Property<std::string>& OpenSim::TransformAxis::getCoordinateNames () const inline
Get the generalized coordinate names associated with this object.
The returned value is a references to the Property<string> that contains the list of coordinate names.
See also
get_coordinates()
getCoordinateNamesInArray()
Array<std::string> OpenSim::TransformAxis::getCoordinateNamesInArray () const inline
Copy the coordinate names into an OpenSim::Array for convenience.
References OpenSim::Array< T >::append().
getFunction()
const Function& OpenSim::TransformAxis::getFunction () const
Get the custom function that maps between the generalized coordinates and the amount of displacement along the specified axis.
If no function has been specified, this throws an exception; check first with hasFunction() if you aren't sure.
getJoint()
const Joint& OpenSim::TransformAxis::getJoint () const inline
Return a reference to the Joint to which this TransformAxis applies.
getValue()
double OpenSim::TransformAxis::getValue (const SimTK::State & s)
hasFunction()
bool OpenSim::TransformAxis::hasFunction () const inline
Determine whether a custom function has been specified to map between the generalized coordinate and the amount of transformation along the specified axis.
safeDownCast()
static TransformAxis* OpenSim::TransformAxis::safeDownCast (OpenSim::Object * obj) inline static
For use in MATLAB and Python to access the concrete class.
Example: cObj = TransformAxis.safeDownCast(obj). This is equivalent to dynamic_cast<TransformAxis*>(obj) in C++.
set_axis()
void OpenSim::TransformAxis::set_axis (const SimTK::Vec3 & value) inline
Set the value of the axis property.
set_coordinates()
void OpenSim::TransformAxis::set_coordinates (int i, const std::string & value) inline
Set the value of the i-th element of coordinates property.
set_function()
void OpenSim::TransformAxis::set_function (const Function & value) inline
Set the value of the function property.
setAxis()
void OpenSim::TransformAxis::setAxis (const SimTK::Vec3 & axis) inline
Set the value of the "axis" property.
setCoordinateNames()
void OpenSim::TransformAxis::setCoordinateNames (const Array< std::string > & coordNames) inline
Set the names of the generalized coordinates that affect the motion along the axis controlled by this TransformAxis object.
Parameters
coordNames Names of the generalized coordinates.
setFunction() [1/2]
void OpenSim::TransformAxis::setFunction (Function * function)
Set the custom function that maps between the generalized coordinates and the amount of displacement about/along the specified axis.
This object adopts ownership of the Function object, don't delete it yourself! It will be deleted when this TransformAxis object is deleted.
setFunction() [2/2]
void OpenSim::TransformAxis::setFunction (const Function & function)
Set the custom function that maps between the generalized coordinates and the amount of transformation about/along the specified axis.
This method creates a copy of the supplied Function object, which is unaffected. Use the other signature if you want this TransformAxis to take over ownership of the Function object.
upd_axis()
SimTK::Vec3& OpenSim::TransformAxis::upd_axis () inline
Get a writable reference to the axis property.
upd_coordinates()
std::string& OpenSim::TransformAxis::upd_coordinates (int i) inline
Get a writable reference to the i-th element of the coordinates property.
upd_function()
Function& OpenSim::TransformAxis::upd_function () inline
Get a writable reference to the function property.
updFunction()
Function& OpenSim::TransformAxis::updFunction ()
Get writable access to the transform function.
OpenSim Property, Socket, Output, Input Documentation
axis
SimTK::Vec3 OpenSim::TransformAxis::axis
"Rotation or translation axis for the transform."
This property appears in XML files under the tag <axis>. This property was generated with the OpenSim_DECLARE_PROPERTY macro; see Property to learn about the property system.
See also
get_axis(), upd_axis(), set_axis()
coordinates
std::string OpenSim::TransformAxis::coordinates
"Names of the coordinates that serve as the independent variables \ of the transform function."
This property appears in XML files under the tag <coordinates>. This property holds a list of objects, and was generated with the OpenSim_DECLARE_LIST_PROPERTY macro; see Property to learn about the property system.
See also
get_coordinates(), upd_coordinates(), set_coordinates(), append_coordinates()
function
Function OpenSim::TransformAxis::function
"Transform function of the generalized coordinates used to \ represent the amount of displacement along a specified axis."
This property appears in XML files under the tag <function>. This property was generated with the OpenSim_DECLARE_PROPERTY macro; see Property to learn about the property system.
See also
get_function(), upd_function(), set_function()
The documentation for this class was generated from the following file:
OpenSim/Simulation/SimbodyEngine/TransformAxis.h